// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension RedshiftClientTypes {
    /// The AQUA (Advanced Query Accelerator) configuration of the cluster.
    public struct AquaConfiguration: Swift.Equatable {
        /// The value represents how the cluster is configured to use AQUA. Possible values include the following.
        ///
        /// * enabled - Use AQUA if it is available for the current Amazon Web Services Region and Amazon Redshift node type.
        ///
        /// * disabled - Don't use AQUA.
        ///
        /// * auto - Amazon Redshift determines whether to use AQUA.
        public var aquaConfigurationStatus: RedshiftClientTypes.AquaConfigurationStatus?
        /// The value indicates the status of AQUA on the cluster. Possible values include the following.
        ///
        /// * enabled - AQUA is enabled.
        ///
        /// * disabled - AQUA is not enabled.
        ///
        /// * applying - AQUA status is being applied.
        public var aquaStatus: RedshiftClientTypes.AquaStatus?

        public init (
            aquaConfigurationStatus: RedshiftClientTypes.AquaConfigurationStatus? = nil,
            aquaStatus: RedshiftClientTypes.AquaStatus? = nil
        )
        {
            self.aquaConfigurationStatus = aquaConfigurationStatus
            self.aquaStatus = aquaStatus
        }
    }

}
