// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

/// Describes the status of logging for a cluster.
public struct EnableLoggingOutputResponse: Swift.Equatable {
    /// The name of the S3 bucket where the log files are stored.
    public var bucketName: Swift.String?
    /// The message indicating that logs failed to be delivered.
    public var lastFailureMessage: Swift.String?
    /// The last time when logs failed to be delivered.
    public var lastFailureTime: ClientRuntime.Date?
    /// The last time that logs were delivered.
    public var lastSuccessfulDeliveryTime: ClientRuntime.Date?
    /// true if logging is on, false if logging is off.
    public var loggingEnabled: Swift.Bool
    /// The prefix applied to the log file names.
    public var s3KeyPrefix: Swift.String?

    public init (
        bucketName: Swift.String? = nil,
        lastFailureMessage: Swift.String? = nil,
        lastFailureTime: ClientRuntime.Date? = nil,
        lastSuccessfulDeliveryTime: ClientRuntime.Date? = nil,
        loggingEnabled: Swift.Bool = false,
        s3KeyPrefix: Swift.String? = nil
    )
    {
        self.bucketName = bucketName
        self.lastFailureMessage = lastFailureMessage
        self.lastFailureTime = lastFailureTime
        self.lastSuccessfulDeliveryTime = lastSuccessfulDeliveryTime
        self.loggingEnabled = loggingEnabled
        self.s3KeyPrefix = s3KeyPrefix
    }
}
