// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct CreateAlertInput: Swift.Equatable {
    /// Action that will be triggered when there is an alert.
    /// This member is required.
    public var action: LookoutMetricsClientTypes.Action?
    /// A description of the alert.
    public var alertDescription: Swift.String?
    /// The name of the alert.
    /// This member is required.
    public var alertName: Swift.String?
    /// An integer from 0 to 100 specifying the alert sensitivity threshold.
    /// This member is required.
    public var alertSensitivityThreshold: Swift.Int
    /// The ARN of the detector to which the alert is attached.
    /// This member is required.
    public var anomalyDetectorArn: Swift.String?
    /// A list of [tags](https://docs.aws.amazon.com/lookoutmetrics/latest/dev/detectors-tags.html) to apply to the alert.
    public var tags: [Swift.String:Swift.String]?

    public init (
        action: LookoutMetricsClientTypes.Action? = nil,
        alertDescription: Swift.String? = nil,
        alertName: Swift.String? = nil,
        alertSensitivityThreshold: Swift.Int = 0,
        anomalyDetectorArn: Swift.String? = nil,
        tags: [Swift.String:Swift.String]? = nil
    )
    {
        self.action = action
        self.alertDescription = alertDescription
        self.alertName = alertName
        self.alertSensitivityThreshold = alertSensitivityThreshold
        self.anomalyDetectorArn = anomalyDetectorArn
        self.tags = tags
    }
}
