// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Represents the input to [CreateDBInstance].
public struct CreateDBInstanceInput: Swift.Equatable {
    /// This parameter does not apply to Amazon DocumentDB. Amazon DocumentDB does not perform minor version upgrades regardless of the value set. Default: false
    public var autoMinorVersionUpgrade: Swift.Bool?
    /// The Amazon EC2 Availability Zone that the instance is created in. Default: A random, system-chosen Availability Zone in the endpoint's Region. Example: us-east-1d
    public var availabilityZone: Swift.String?
    /// The identifier of the cluster that the instance will belong to.
    /// This member is required.
    public var dBClusterIdentifier: Swift.String?
    /// The compute and memory capacity of the instance; for example, db.r5.large.
    /// This member is required.
    public var dBInstanceClass: Swift.String?
    /// The instance identifier. This parameter is stored as a lowercase string. Constraints:
    ///
    /// * Must contain from 1 to 63 letters, numbers, or hyphens.
    ///
    /// * The first character must be a letter.
    ///
    /// * Cannot end with a hyphen or contain two consecutive hyphens.
    ///
    ///
    /// Example: mydbinstance
    /// This member is required.
    public var dBInstanceIdentifier: Swift.String?
    /// The name of the database engine to be used for this instance. Valid value: docdb
    /// This member is required.
    public var engine: Swift.String?
    /// The time range each week during which system maintenance can occur, in Universal Coordinated Time (UTC). Format: ddd:hh24:mi-ddd:hh24:mi The default is a 30-minute window selected at random from an 8-hour block of time for each Region, occurring on a random day of the week. Valid days: Mon, Tue, Wed, Thu, Fri, Sat, Sun Constraints: Minimum 30-minute window.
    public var preferredMaintenanceWindow: Swift.String?
    /// A value that specifies the order in which an Amazon DocumentDB replica is promoted to the primary instance after a failure of the existing primary instance. Default: 1 Valid values: 0-15
    public var promotionTier: Swift.Int?
    /// The tags to be assigned to the instance. You can assign up to 10 tags to an instance.
    public var tags: [DocDbClientTypes.Tag]?

    public init (
        autoMinorVersionUpgrade: Swift.Bool? = nil,
        availabilityZone: Swift.String? = nil,
        dBClusterIdentifier: Swift.String? = nil,
        dBInstanceClass: Swift.String? = nil,
        dBInstanceIdentifier: Swift.String? = nil,
        engine: Swift.String? = nil,
        preferredMaintenanceWindow: Swift.String? = nil,
        promotionTier: Swift.Int? = nil,
        tags: [DocDbClientTypes.Tag]? = nil
    )
    {
        self.autoMinorVersionUpgrade = autoMinorVersionUpgrade
        self.availabilityZone = availabilityZone
        self.dBClusterIdentifier = dBClusterIdentifier
        self.dBInstanceClass = dBInstanceClass
        self.dBInstanceIdentifier = dBInstanceIdentifier
        self.engine = engine
        self.preferredMaintenanceWindow = preferredMaintenanceWindow
        self.promotionTier = promotionTier
        self.tags = tags
    }
}
