// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension UpdateSMBFileShareVisibilityInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case fileSharesVisible = "FileSharesVisible"
        case gatewayARN = "GatewayARN"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let fileSharesVisible = fileSharesVisible {
            try encodeContainer.encode(fileSharesVisible, forKey: .fileSharesVisible)
        }
        if let gatewayARN = gatewayARN {
            try encodeContainer.encode(gatewayARN, forKey: .gatewayARN)
        }
    }
}
