// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension Ec2ClientTypes {
    /// The tags specification for the launch template.
    public struct LaunchTemplateTagSpecificationRequest: Swift.Equatable {
        /// The type of resource to tag. Currently, the resource types that support tagging on creation are instance and volume. To tag a resource after it has been created, see [CreateTags](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTags.html).
        public var resourceType: Ec2ClientTypes.ResourceType?
        /// The tags to apply to the resource.
        public var tags: [Ec2ClientTypes.Tag]?

        public init (
            resourceType: Ec2ClientTypes.ResourceType? = nil,
            tags: [Ec2ClientTypes.Tag]? = nil
        )
        {
            self.resourceType = resourceType
            self.tags = tags
        }
    }

}
