// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension OpenSearchClientTypes {
    /// The advanced security configuration: whether advanced security is enabled, whether the internal database option is enabled, master username and password (if internal database is enabled), and master user ARN (if IAM is enabled).
    public struct AdvancedSecurityOptionsInput: Swift.Equatable {
        /// True if advanced security is enabled.
        public var enabled: Swift.Bool?
        /// True if the internal user database is enabled.
        public var internalUserDatabaseEnabled: Swift.Bool?
        /// Credentials for the master user: username and password, ARN, or both.
        public var masterUserOptions: OpenSearchClientTypes.MasterUserOptions?
        /// The SAML application configuration for the domain.
        public var sAMLOptions: OpenSearchClientTypes.SAMLOptionsInput?

        public init (
            enabled: Swift.Bool? = nil,
            internalUserDatabaseEnabled: Swift.Bool? = nil,
            masterUserOptions: OpenSearchClientTypes.MasterUserOptions? = nil,
            sAMLOptions: OpenSearchClientTypes.SAMLOptionsInput? = nil
        )
        {
            self.enabled = enabled
            self.internalUserDatabaseEnabled = internalUserDatabaseEnabled
            self.masterUserOptions = masterUserOptions
            self.sAMLOptions = sAMLOptions
        }
    }

}
