// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

/// DescribeLocationObjectStorageResponse
public struct DescribeLocationObjectStorageOutputResponse: Swift.Equatable {
    /// Optional. The access key is used if credentials are required to access the self-managed object storage server. If your object storage requires a user name and password to authenticate, use AccessKey and SecretKey to provide the user name and password, respectively.
    public var accessKey: Swift.String?
    /// The Amazon Resource Name (ARN) of the agents associated with the self-managed object storage server location.
    public var agentArns: [Swift.String]?
    /// The time that the self-managed object storage server agent was created.
    public var creationTime: ClientRuntime.Date?
    /// The Amazon Resource Name (ARN) of the self-managed object storage server location to describe.
    public var locationArn: Swift.String?
    /// The URL of the source self-managed object storage server location that was described.
    public var locationUri: Swift.String?
    /// The port that your self-managed object storage server accepts inbound network traffic on. The server port is set by default to TCP 80 (HTTP) or TCP 443 (HTTPS).
    public var serverPort: Swift.Int?
    /// The protocol that the object storage server uses to communicate. Valid values are HTTP or HTTPS.
    public var serverProtocol: DataSyncClientTypes.ObjectStorageServerProtocol?

    public init (
        accessKey: Swift.String? = nil,
        agentArns: [Swift.String]? = nil,
        creationTime: ClientRuntime.Date? = nil,
        locationArn: Swift.String? = nil,
        locationUri: Swift.String? = nil,
        serverPort: Swift.Int? = nil,
        serverProtocol: DataSyncClientTypes.ObjectStorageServerProtocol? = nil
    )
    {
        self.accessKey = accessKey
        self.agentArns = agentArns
        self.creationTime = creationTime
        self.locationArn = locationArn
        self.locationUri = locationUri
        self.serverPort = serverPort
        self.serverProtocol = serverProtocol
    }
}
