// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension DataSyncClientTypes {
    /// You can use API filters to narrow down the list of resources returned by ListLocations. For example, to retrieve all your Amazon S3 locations, you can use ListLocations with filter name LocationType S3 and Operator Equals.
    public struct LocationFilter: Swift.Equatable {
        /// The name of the filter being used. Each API call supports a list of filters that are available for it (for example, LocationType for ListLocations).
        /// This member is required.
        public var name: DataSyncClientTypes.LocationFilterName?
        /// The operator that is used to compare filter values (for example, Equals or Contains). For more about API filtering operators, see [API filters for ListTasks and ListLocations](https://docs.aws.amazon.com/datasync/latest/userguide/query-resources.html).
        /// This member is required.
        public var `operator`: DataSyncClientTypes.Operator?
        /// The values that you want to filter for. For example, you might want to display only Amazon S3 locations.
        /// This member is required.
        public var values: [Swift.String]?

        public init (
            name: DataSyncClientTypes.LocationFilterName? = nil,
            `operator`: DataSyncClientTypes.Operator? = nil,
            values: [Swift.String]? = nil
        )
        {
            self.name = name
            self.`operator` = `operator`
            self.values = values
        }
    }

}
