// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension ListMembersInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case maxResults
        case nextToken
        case onlyAssociated
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let maxResults = maxResults {
            try encodeContainer.encode(maxResults, forKey: .maxResults)
        }
        if let nextToken = nextToken {
            try encodeContainer.encode(nextToken, forKey: .nextToken)
        }
        if let onlyAssociated = onlyAssociated {
            try encodeContainer.encode(onlyAssociated, forKey: .onlyAssociated)
        }
    }
}
