// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension CognitoIdentityProviderClientTypes {
    /// Contextual user data type used for evaluating the risk of an unexpected event by Amazon Cognito advanced security.
    public struct ContextDataType: Swift.Equatable {
        /// Encoded data containing device fingerprinting details, collected using the Amazon Cognito context data collection library.
        public var encodedData: Swift.String?
        /// HttpHeaders received on your server in same order.
        /// This member is required.
        public var httpHeaders: [CognitoIdentityProviderClientTypes.HttpHeader]?
        /// Source IP address of your user.
        /// This member is required.
        public var ipAddress: Swift.String?
        /// Your server endpoint where this API is invoked.
        /// This member is required.
        public var serverName: Swift.String?
        /// Your server path where this API is invoked.
        /// This member is required.
        public var serverPath: Swift.String?

        public init (
            encodedData: Swift.String? = nil,
            httpHeaders: [CognitoIdentityProviderClientTypes.HttpHeader]? = nil,
            ipAddress: Swift.String? = nil,
            serverName: Swift.String? = nil,
            serverPath: Swift.String? = nil
        )
        {
            self.encodedData = encodedData
            self.httpHeaders = httpHeaders
            self.ipAddress = ipAddress
            self.serverName = serverName
            self.serverPath = serverPath
        }
    }

}
