// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension CognitoIdentityProviderClientTypes {
    /// A container for information about an identity provider for a user pool.
    public struct ProviderUserIdentifierType: Swift.Equatable {
        /// The name of the provider attribute to link to, for example, NameID.
        public var providerAttributeName: Swift.String?
        /// The value of the provider attribute to link to, for example, xxxxx_account.
        public var providerAttributeValue: Swift.String?
        /// The name of the provider, for example, Facebook, Google, or Login with Amazon.
        public var providerName: Swift.String?

        public init (
            providerAttributeName: Swift.String? = nil,
            providerAttributeValue: Swift.String? = nil,
            providerName: Swift.String? = nil
        )
        {
            self.providerAttributeName = providerAttributeName
            self.providerAttributeValue = providerAttributeValue
            self.providerName = providerName
        }
    }

}
