// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct SetUserPoolMfaConfigInput: Swift.Equatable {
    /// The MFA configuration. Users who don't have an MFA factor set up won't be able to sign-in if you set the MfaConfiguration value to ‘ON’. See [Adding Multi-Factor Authentication (MFA) to a User Pool] to learn more. Valid values include:
    ///
    /// * OFF MFA will not be used for any users.
    ///
    /// * ON MFA is required for all users to sign in.
    ///
    /// * OPTIONAL MFA will be required only for individual users who have an MFA factor enabled.
    public var mfaConfiguration: CognitoIdentityProviderClientTypes.UserPoolMfaType?
    /// The SMS text message MFA configuration.
    public var smsMfaConfiguration: CognitoIdentityProviderClientTypes.SmsMfaConfigType?
    /// The software token MFA configuration.
    public var softwareTokenMfaConfiguration: CognitoIdentityProviderClientTypes.SoftwareTokenMfaConfigType?
    /// The user pool ID.
    /// This member is required.
    public var userPoolId: Swift.String?

    public init (
        mfaConfiguration: CognitoIdentityProviderClientTypes.UserPoolMfaType? = nil,
        smsMfaConfiguration: CognitoIdentityProviderClientTypes.SmsMfaConfigType? = nil,
        softwareTokenMfaConfiguration: CognitoIdentityProviderClientTypes.SoftwareTokenMfaConfigType? = nil,
        userPoolId: Swift.String? = nil
    )
    {
        self.mfaConfiguration = mfaConfiguration
        self.smsMfaConfiguration = smsMfaConfiguration
        self.softwareTokenMfaConfiguration = softwareTokenMfaConfiguration
        self.userPoolId = userPoolId
    }
}
