// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DisablePolicyTypeInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case policyType = "PolicyType"
        case rootId = "RootId"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let policyType = policyType {
            try encodeContainer.encode(policyType.rawValue, forKey: .policyType)
        }
        if let rootId = rootId {
            try encodeContainer.encode(rootId, forKey: .rootId)
        }
    }
}
