// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct SyncDeploymentJobInput: Swift.Equatable {
    /// Unique, case-sensitive identifier that you provide to ensure the idempotency of the request.
    /// This member is required.
    public var clientRequestToken: Swift.String?
    /// The target fleet for the synchronization.
    /// This member is required.
    public var fleet: Swift.String?

    public init (
        clientRequestToken: Swift.String? = nil,
        fleet: Swift.String? = nil
    )
    {
        self.clientRequestToken = clientRequestToken
        self.fleet = fleet
    }
}
