// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension MwaaClientTypes {
    /// Internal only API.
    public struct Dimension: Swift.Equatable {
        /// Internal only API.
        /// This member is required.
        public var name: Swift.String?
        /// Internal only API.
        /// This member is required.
        public var value: Swift.String?

        public init (
            name: Swift.String? = nil,
            value: Swift.String? = nil
        )
        {
            self.name = name
            self.value = value
        }
    }

}
