// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension MwaaClientTypes {
    /// The status of the last update on the environment, and any errors that were encountered.
    public struct LastUpdate: Swift.Equatable {
        /// The day and time of the last update on the environment.
        public var createdAt: ClientRuntime.Date?
        /// The error that was encountered during the last update of the environment.
        public var error: MwaaClientTypes.UpdateError?
        /// The status of the last update on the environment. Valid values: SUCCESS, PENDING, FAILED.
        public var status: MwaaClientTypes.UpdateStatus?

        public init (
            createdAt: ClientRuntime.Date? = nil,
            error: MwaaClientTypes.UpdateError? = nil,
            status: MwaaClientTypes.UpdateStatus? = nil
        )
        {
            self.createdAt = createdAt
            self.error = error
            self.status = status
        }
    }

}
