// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SyntheticsClientTypes {
    /// If this canary performs visual monitoring by comparing screenshots, this structure contains the ID of the canary run that is used as the baseline for screenshots, and the coordinates of any parts of those screenshots that are ignored during visual monitoring comparison. Visual monitoring is supported only on canaries running the syn-puppeteer-node-3.2 runtime or later.
    public struct VisualReferenceOutput: Swift.Equatable {
        /// The ID of the canary run that produced the screenshots that are used as the baseline for visual monitoring comparisons during future runs of this canary.
        public var baseCanaryRunId: Swift.String?
        /// An array of screenshots that are used as the baseline for comparisons during visual monitoring.
        public var baseScreenshots: [SyntheticsClientTypes.BaseScreenshot]?

        public init (
            baseCanaryRunId: Swift.String? = nil,
            baseScreenshots: [SyntheticsClientTypes.BaseScreenshot]? = nil
        )
        {
            self.baseCanaryRunId = baseCanaryRunId
            self.baseScreenshots = baseScreenshots
        }
    }

}
