// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension BudgetsClientTypes {
    /// A notification that is associated with a budget. A budget can have up to ten notifications. Each notification must have at least one subscriber. A notification can have one SNS subscriber and up to 10 email subscribers, for a total of 11 subscribers. For example, if you have a budget for 200 dollars and you want to be notified when you go over 160 dollars, create a notification with the following parameters:
    ///
    /// * A notificationType of ACTUAL
    ///
    /// * A thresholdType of PERCENTAGE
    ///
    /// * A comparisonOperator of GREATER_THAN
    ///
    /// * A notification threshold of 80
    public struct Notification: Swift.Equatable {
        /// The comparison that is used for this notification.
        /// This member is required.
        public var comparisonOperator: BudgetsClientTypes.ComparisonOperator?
        /// Whether this notification is in alarm. If a budget notification is in the ALARM state, you have passed the set threshold for the budget.
        public var notificationState: BudgetsClientTypes.NotificationState?
        /// Whether the notification is for how much you have spent (ACTUAL) or for how much you're forecasted to spend (FORECASTED).
        /// This member is required.
        public var notificationType: BudgetsClientTypes.NotificationType?
        /// The threshold that is associated with a notification. Thresholds are always a percentage, and many customers find value being alerted between 50% - 200% of the budgeted amount. The maximum limit for your threshold is 1,000,000% above the budgeted amount.
        /// This member is required.
        public var threshold: Swift.Double
        /// The type of threshold for a notification. For ABSOLUTE_VALUE thresholds, AWS notifies you when you go over or are forecasted to go over your total cost threshold. For PERCENTAGE thresholds, AWS notifies you when you go over or are forecasted to go over a certain percentage of your forecasted spend. For example, if you have a budget for 200 dollars and you have a PERCENTAGE threshold of 80%, AWS notifies you when you go over 160 dollars.
        public var thresholdType: BudgetsClientTypes.ThresholdType?

        public init (
            comparisonOperator: BudgetsClientTypes.ComparisonOperator? = nil,
            notificationState: BudgetsClientTypes.NotificationState? = nil,
            notificationType: BudgetsClientTypes.NotificationType? = nil,
            threshold: Swift.Double = 0.0,
            thresholdType: BudgetsClientTypes.ThresholdType? = nil
        )
        {
            self.comparisonOperator = comparisonOperator
            self.notificationState = notificationState
            self.notificationType = notificationType
            self.threshold = threshold
            self.thresholdType = thresholdType
        }
    }

}
