// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension IotWirelessClientTypes {
    /// Device registration state event configuration object for enabling and disabling relevant topics.
    public struct DeviceRegistrationStateEventConfiguration: Swift.Equatable {
        /// Device registration state event configuration object for enabling or disabling Sidewalk related event topics.
        public var sidewalk: IotWirelessClientTypes.SidewalkEventNotificationConfigurations?

        public init (
            sidewalk: IotWirelessClientTypes.SidewalkEventNotificationConfigurations? = nil
        )
        {
            self.sidewalk = sidewalk
        }
    }

}
