// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension IotWirelessClientTypes {
    /// SidewalkEventNotificationConfigurations object Event configuration object for Sidewalk related event topics.
    public struct SidewalkEventNotificationConfigurations: Swift.Equatable {
        /// Enum to denote whether amazon id event topic is enabled or disabled.
        public var amazonIdEventTopic: IotWirelessClientTypes.EventNotificationTopicStatus?

        public init (
            amazonIdEventTopic: IotWirelessClientTypes.EventNotificationTopicStatus? = nil
        )
        {
            self.amazonIdEventTopic = amazonIdEventTopic
        }
    }

}
