// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension CloudControlClientTypes {
    /// The filter criteria to use in determining the requests returned.
    public struct ResourceRequestStatusFilter: Swift.Equatable {
        /// The operation statuses to include in the filter.
        ///
        /// * PENDING: The operation has been requested, but not yet initiated.
        ///
        /// * IN_PROGRESS: The operation is currently in progress.
        ///
        /// * SUCCESS: The operation has successfully completed.
        ///
        /// * FAILED: The operation has failed.
        ///
        /// * CANCEL_IN_PROGRESS: The operation is currently in the process of being canceled.
        ///
        /// * CANCEL_COMPLETE: The operation has been canceled.
        public var operationStatuses: [CloudControlClientTypes.OperationStatus]?
        /// The operation types to include in the filter.
        public var operations: [CloudControlClientTypes.Operation]?

        public init (
            operationStatuses: [CloudControlClientTypes.OperationStatus]? = nil,
            operations: [CloudControlClientTypes.Operation]? = nil
        )
        {
            self.operationStatuses = operationStatuses
            self.operations = operations
        }
    }

}
