// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ExportComponentsOutputResponse: Swift.Equatable {
    /// Represents the configuration of the exported components.
    /// This member is required.
    public var entities: [AmplifyUiBuilderClientTypes.Component]?

    public init (
        entities: [AmplifyUiBuilderClientTypes.Component]? = nil
    )
    {
        self.entities = entities
    }
}
