// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ExportThemesOutputResponse: Swift.Equatable {
    /// Represents the configuration of the exported themes.
    /// This member is required.
    public var entities: [AmplifyUiBuilderClientTypes.Theme]?

    public init (
        entities: [AmplifyUiBuilderClientTypes.Theme]? = nil
    )
    {
        self.entities = entities
    }
}
