// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension TimestreamWriteClientTypes.RecordsIngested: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case magneticStore = "MagneticStore"
        case memoryStore = "MemoryStore"
        case total = "Total"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if magneticStore != 0 {
            try encodeContainer.encode(magneticStore, forKey: .magneticStore)
        }
        if memoryStore != 0 {
            try encodeContainer.encode(memoryStore, forKey: .memoryStore)
        }
        if total != 0 {
            try encodeContainer.encode(total, forKey: .total)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let totalDecoded = try containerValues.decode(Swift.Int.self, forKey: .total)
        total = totalDecoded
        let memoryStoreDecoded = try containerValues.decode(Swift.Int.self, forKey: .memoryStore)
        memoryStore = memoryStoreDecoded
        let magneticStoreDecoded = try containerValues.decode(Swift.Int.self, forKey: .magneticStore)
        magneticStore = magneticStoreDecoded
    }
}
