// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension CreatePresetInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case audio = "Audio"
        case container = "Container"
        case description = "Description"
        case name = "Name"
        case thumbnails = "Thumbnails"
        case video = "Video"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let audio = audio {
            try encodeContainer.encode(audio, forKey: .audio)
        }
        if let container = container {
            try encodeContainer.encode(container, forKey: .container)
        }
        if let description = description {
            try encodeContainer.encode(description, forKey: .description)
        }
        if let name = name {
            try encodeContainer.encode(name, forKey: .name)
        }
        if let thumbnails = thumbnails {
            try encodeContainer.encode(thumbnails, forKey: .thumbnails)
        }
        if let video = video {
            try encodeContainer.encode(video, forKey: .video)
        }
    }
}
