// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension GuardDutyClientTypes {
    /// Contains information about the API action.
    public struct AwsApiCallAction: Swift.Equatable {
        /// The AWS API name.
        public var api: Swift.String?
        /// The AWS API caller type.
        public var callerType: Swift.String?
        /// The domain information for the AWS API call.
        public var domainDetails: GuardDutyClientTypes.DomainDetails?
        /// The error code of the failed AWS API action.
        public var errorCode: Swift.String?
        /// The remote IP information of the connection that initiated the AWS API call.
        public var remoteIpDetails: GuardDutyClientTypes.RemoteIpDetails?
        /// The AWS service name whose API was invoked.
        public var serviceName: Swift.String?

        public init (
            api: Swift.String? = nil,
            callerType: Swift.String? = nil,
            domainDetails: GuardDutyClientTypes.DomainDetails? = nil,
            errorCode: Swift.String? = nil,
            remoteIpDetails: GuardDutyClientTypes.RemoteIpDetails? = nil,
            serviceName: Swift.String? = nil
        )
        {
            self.api = api
            self.callerType = callerType
            self.domainDetails = domainDetails
            self.errorCode = errorCode
            self.remoteIpDetails = remoteIpDetails
            self.serviceName = serviceName
        }
    }

}
