// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DescribeAppVersionResourcesResolutionStatusInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case appArn
        case appVersion
        case resolutionId
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let appArn = appArn {
            try encodeContainer.encode(appArn, forKey: .appArn)
        }
        if let appVersion = appVersion {
            try encodeContainer.encode(appVersion, forKey: .appVersion)
        }
        if let resolutionId = resolutionId {
            try encodeContainer.encode(resolutionId, forKey: .resolutionId)
        }
    }
}
