// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct UpdateAppInput: Swift.Equatable {
    /// The Amazon Resource Name (ARN) of the application. The format for this ARN is: arn:partition:dcps:region:account:app/app-id. For more information about ARNs, see [ Amazon Resource Names (ARNs)](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) in the AWS General Reference.
    /// This member is required.
    public var appArn: Swift.String?
    /// Specifies if the resiliency policy ARN should be cleared.
    public var clearResiliencyPolicyArn: Swift.Bool?
    /// The optional description for an app.
    public var description: Swift.String?
    /// The Amazon Resource Name (ARN) of the resiliency policy. The format for this ARN is: arn:partition:dcps:region:account:resiliency-policy/policy-id. For more information about ARNs, see [ Amazon Resource Names (ARNs)](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) in the AWS General Reference.
    public var policyArn: Swift.String?

    public init (
        appArn: Swift.String? = nil,
        clearResiliencyPolicyArn: Swift.Bool? = nil,
        description: Swift.String? = nil,
        policyArn: Swift.String? = nil
    )
    {
        self.appArn = appArn
        self.clearResiliencyPolicyArn = clearResiliencyPolicyArn
        self.description = description
        self.policyArn = policyArn
    }
}
