// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Input for update lens review.
public struct UpdateLensReviewInput: Swift.Equatable {
    /// The alias of the lens, for example, serverless. Each lens is identified by its [LensSummary$LensAlias].
    /// This member is required.
    public var lensAlias: Swift.String?
    /// The notes associated with the workload.
    public var lensNotes: Swift.String?
    /// List of pillar notes of a lens review in a workload.
    public var pillarNotes: [Swift.String:Swift.String]?
    /// The ID assigned to the workload. This ID is unique within an Amazon Web Services Region.
    /// This member is required.
    public var workloadId: Swift.String?

    public init (
        lensAlias: Swift.String? = nil,
        lensNotes: Swift.String? = nil,
        pillarNotes: [Swift.String:Swift.String]? = nil,
        workloadId: Swift.String? = nil
    )
    {
        self.lensAlias = lensAlias
        self.lensNotes = lensNotes
        self.pillarNotes = pillarNotes
        self.workloadId = workloadId
    }
}
