// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension EcrClientTypes {
    /// The details of a scanning rule for a private registry.
    public struct RegistryScanningRule: Swift.Equatable {
        /// The repository filters associated with the scanning configuration for a private registry.
        /// This member is required.
        public var repositoryFilters: [EcrClientTypes.ScanningRepositoryFilter]?
        /// The frequency that scans are performed at for a private registry.
        /// This member is required.
        public var scanFrequency: EcrClientTypes.ScanFrequency?

        public init (
            repositoryFilters: [EcrClientTypes.ScanningRepositoryFilter]? = nil,
            scanFrequency: EcrClientTypes.ScanFrequency? = nil
        )
        {
            self.repositoryFilters = repositoryFilters
            self.scanFrequency = scanFrequency
        }
    }

}
