// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension AddJobFlowStepsInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case jobFlowId = "JobFlowId"
        case steps = "Steps"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let jobFlowId = jobFlowId {
            try encodeContainer.encode(jobFlowId, forKey: .jobFlowId)
        }
        if let steps = steps {
            var stepsContainer = encodeContainer.nestedUnkeyedContainer(forKey: .steps)
            for stepconfiglist0 in steps {
                try stepsContainer.encode(stepconfiglist0)
            }
        }
    }
}
