// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DeleteBucketAccessKeyInput: Swift.Equatable {
    /// The ID of the access key to delete. Use the [GetBucketAccessKeys] action to get a list of access key IDs that you can specify.
    /// This member is required.
    public var accessKeyId: Swift.String?
    /// The name of the bucket that the access key belongs to.
    /// This member is required.
    public var bucketName: Swift.String?

    public init (
        accessKeyId: Swift.String? = nil,
        bucketName: Swift.String? = nil
    )
    {
        self.accessKeyId = accessKeyId
        self.bucketName = bucketName
    }
}
