// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DownloadDefaultKeyPairOutputResponse: Swift.Equatable {
    /// A base64-encoded RSA private key.
    public var privateKeyBase64: Swift.String?
    /// A base64-encoded public key of the ssh-rsa type.
    public var publicKeyBase64: Swift.String?

    public init (
        privateKeyBase64: Swift.String? = nil,
        publicKeyBase64: Swift.String? = nil
    )
    {
        self.privateKeyBase64 = privateKeyBase64
        self.publicKeyBase64 = publicKeyBase64
    }
}
