// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension S3ClientTypes {
    /// Container for all response elements.
    public struct CopyPartResult: Swift.Equatable {
        /// Entity tag of the object.
        public var eTag: Swift.String?
        /// Date and time at which the object was uploaded.
        public var lastModified: ClientRuntime.Date?

        public init (
            eTag: Swift.String? = nil,
            lastModified: ClientRuntime.Date? = nil
        )
        {
            self.eTag = eTag
            self.lastModified = lastModified
        }
    }

}
