// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct PutBucketVersioningInput: Swift.Equatable {
    /// The bucket name.
    /// This member is required.
    public var bucket: Swift.String?
    /// >The base64-encoded 128-bit MD5 digest of the data. You must use this header as a message integrity check to verify that the request body was not corrupted in transit. For more information, see [RFC 1864](http://www.ietf.org/rfc/rfc1864.txt). For requests made using the Amazon Web Services Command Line Interface (CLI) or Amazon Web Services SDKs, this field is calculated automatically.
    public var contentMD5: Swift.String?
    /// The account ID of the expected bucket owner. If the bucket is owned by a different account, the request will fail with an HTTP 403 (Access Denied) error.
    public var expectedBucketOwner: Swift.String?
    /// The concatenation of the authentication device's serial number, a space, and the value that is displayed on your authentication device.
    public var mFA: Swift.String?
    /// Container for setting the versioning state.
    /// This member is required.
    public var versioningConfiguration: S3ClientTypes.VersioningConfiguration?

    public init (
        bucket: Swift.String? = nil,
        contentMD5: Swift.String? = nil,
        expectedBucketOwner: Swift.String? = nil,
        mFA: Swift.String? = nil,
        versioningConfiguration: S3ClientTypes.VersioningConfiguration? = nil
    )
    {
        self.bucket = bucket
        self.contentMD5 = contentMD5
        self.expectedBucketOwner = expectedBucketOwner
        self.mFA = mFA
        self.versioningConfiguration = versioningConfiguration
    }
}
