// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GlueClientTypes.BooleanColumnStatisticsData: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case numberOfFalses = "NumberOfFalses"
        case numberOfNulls = "NumberOfNulls"
        case numberOfTrues = "NumberOfTrues"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if numberOfFalses != 0 {
            try encodeContainer.encode(numberOfFalses, forKey: .numberOfFalses)
        }
        if numberOfNulls != 0 {
            try encodeContainer.encode(numberOfNulls, forKey: .numberOfNulls)
        }
        if numberOfTrues != 0 {
            try encodeContainer.encode(numberOfTrues, forKey: .numberOfTrues)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let numberOfTruesDecoded = try containerValues.decode(Swift.Int.self, forKey: .numberOfTrues)
        numberOfTrues = numberOfTruesDecoded
        let numberOfFalsesDecoded = try containerValues.decode(Swift.Int.self, forKey: .numberOfFalses)
        numberOfFalses = numberOfFalsesDecoded
        let numberOfNullsDecoded = try containerValues.decode(Swift.Int.self, forKey: .numberOfNulls)
        numberOfNulls = numberOfNullsDecoded
    }
}
