// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetBlueprintInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case includeBlueprint = "IncludeBlueprint"
        case includeParameterSpec = "IncludeParameterSpec"
        case name = "Name"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let includeBlueprint = includeBlueprint {
            try encodeContainer.encode(includeBlueprint, forKey: .includeBlueprint)
        }
        if let includeParameterSpec = includeParameterSpec {
            try encodeContainer.encode(includeParameterSpec, forKey: .includeParameterSpec)
        }
        if let name = name {
            try encodeContainer.encode(name, forKey: .name)
        }
    }
}
