// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct CreateCellOutputResponse: Swift.Equatable {
    /// The arn for the Cell
    public var cellArn: Swift.String?
    /// The name of the Cell
    public var cellName: Swift.String?
    /// A list of Cell arns
    public var cells: [Swift.String]?
    /// A list of Cell ARNs and/or RecoveryGroup ARNs
    public var parentReadinessScopes: [Swift.String]?
    /// A collection of tags associated with a resource
    public var tags: [Swift.String:Swift.String]?

    public init (
        cellArn: Swift.String? = nil,
        cellName: Swift.String? = nil,
        cells: [Swift.String]? = nil,
        parentReadinessScopes: [Swift.String]? = nil,
        tags: [Swift.String:Swift.String]? = nil
    )
    {
        self.cellArn = cellArn
        self.cellName = cellName
        self.cells = cells
        self.parentReadinessScopes = parentReadinessScopes
        self.tags = tags
    }
}
