// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DeleteCellInput: Swift.Equatable {
    /// The Cell to delete
    /// This member is required.
    public var cellName: Swift.String?

    public init (
        cellName: Swift.String? = nil
    )
    {
        self.cellName = cellName
    }
}
