// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetCellReadinessSummaryInput: Swift.Equatable {
    /// The name of the Cell
    /// This member is required.
    public var cellName: Swift.String?
    /// Upper bound on number of records to return.
    public var maxResults: Swift.Int
    /// A token used to resume pagination from the end of a previous request.
    public var nextToken: Swift.String?

    public init (
        cellName: Swift.String? = nil,
        maxResults: Swift.Int = 0,
        nextToken: Swift.String? = nil
    )
    {
        self.cellName = cellName
        self.maxResults = maxResults
        self.nextToken = nextToken
    }
}
