// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ListRulesOutputResponse: Swift.Equatable {
    /// A token that can be used to resume pagination from the end of the collection.
    public var nextToken: Swift.String?
    /// A list of rules
    public var rules: [Route53RecoveryReadinessClientTypes.ListRulesOutput]?

    public init (
        nextToken: Swift.String? = nil,
        rules: [Route53RecoveryReadinessClientTypes.ListRulesOutput]? = nil
    )
    {
        self.nextToken = nextToken
        self.rules = rules
    }
}
