// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension Route53RecoveryReadinessClientTypes {
    /// The NLB resource a DNS Target Resource points to
    public struct NLBResource: Swift.Equatable {
        /// An NLB resource arn
        public var arn: Swift.String?

        public init (
            arn: Swift.String? = nil
        )
        {
            self.arn = arn
        }
    }

}
