// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension RbinClientTypes {
    /// Information about a resource tag used to identify resources that are to be retained by a Recycle Bin retention rule.
    public struct ResourceTag: Swift.Equatable {
        /// The tag key.
        /// This member is required.
        public var resourceTagKey: Swift.String?
        /// The tag value.
        public var resourceTagValue: Swift.String?

        public init (
            resourceTagKey: Swift.String? = nil,
            resourceTagValue: Swift.String? = nil
        )
        {
            self.resourceTagKey = resourceTagKey
            self.resourceTagValue = resourceTagValue
        }
    }

}
