// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct TagResourceInput: Swift.Equatable {
    /// The Amazon Resource Name (ARN) of the resource to which to assign the tags.
    /// This member is required.
    public var resourceArn: Swift.String?
    /// Information about the tags to assign to the resource.
    /// This member is required.
    public var tags: [RbinClientTypes.Tag]?

    public init (
        resourceArn: Swift.String? = nil,
        tags: [RbinClientTypes.Tag]? = nil
    )
    {
        self.resourceArn = resourceArn
        self.tags = tags
    }
}
