// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DetectStackSetDriftOutputResponse: Swift.Equatable {
    /// The ID of the drift detection stack set operation. you can use this operation id with [DescribeStackSetOperation] to monitor the progress of the drift detection operation.
    public var operationId: Swift.String?

    public init (
        operationId: Swift.String? = nil
    )
    {
        self.operationId = operationId
    }
}
