// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct UpdateSchedulingPolicyInput: Swift.Equatable {
    /// The Amazon Resource Name (ARN) of the scheduling policy to update.
    /// This member is required.
    public var arn: Swift.String?
    /// The fair share policy.
    public var fairsharePolicy: BatchClientTypes.FairsharePolicy?

    public init (
        arn: Swift.String? = nil,
        fairsharePolicy: BatchClientTypes.FairsharePolicy? = nil
    )
    {
        self.arn = arn
        self.fairsharePolicy = fairsharePolicy
    }
}
