// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension RdsClientTypes {
    /// A custom Availability Zone (AZ) is an on-premises AZ that is integrated with a VMware vSphere cluster. For more information about RDS on VMware, see the [ RDS on VMware User Guide.](https://docs.aws.amazon.com/AmazonRDS/latest/RDSonVMwareUserGuide/rds-on-vmware.html)
    public struct CustomAvailabilityZone: Swift.Equatable {
        /// The identifier of the custom AZ. Amazon RDS generates a unique identifier when a custom AZ is created.
        public var customAvailabilityZoneId: Swift.String?
        /// The name of the custom AZ.
        public var customAvailabilityZoneName: Swift.String?
        /// The status of the custom AZ.
        public var customAvailabilityZoneStatus: Swift.String?
        /// Information about the virtual private network (VPN) between the VMware vSphere cluster and the Amazon Web Services website.
        public var vpnDetails: RdsClientTypes.VpnDetails?

        public init (
            customAvailabilityZoneId: Swift.String? = nil,
            customAvailabilityZoneName: Swift.String? = nil,
            customAvailabilityZoneStatus: Swift.String? = nil,
            vpnDetails: RdsClientTypes.VpnDetails? = nil
        )
        {
            self.customAvailabilityZoneId = customAvailabilityZoneId
            self.customAvailabilityZoneName = customAvailabilityZoneName
            self.customAvailabilityZoneStatus = customAvailabilityZoneStatus
            self.vpnDetails = vpnDetails
        }
    }

}
