// Code generated by smithy-swift-codegen. DO NOT EDIT!

import AWSClientRuntime

public enum DescribeInstallationMediaOutputError: Swift.Error, Swift.Equatable {
    case installationMediaNotFoundFault(InstallationMediaNotFoundFault)
    case unknown(UnknownAWSHttpServiceError)
}
