// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension LocationClientTypes {
    /// Contains geofence geometry details.
    public struct BatchPutGeofenceRequestEntry: Swift.Equatable {
        /// The identifier for the geofence to be stored in a given geofence collection.
        /// This member is required.
        public var geofenceId: Swift.String?
        /// Contains the polygon details to specify the position of the geofence. Each [geofence polygon](https://docs.aws.amazon.com/location-geofences/latest/APIReference/API_GeofenceGeometry.html) can have a maximum of 1,000 vertices.
        /// This member is required.
        public var geometry: LocationClientTypes.GeofenceGeometry?

        public init (
            geofenceId: Swift.String? = nil,
            geometry: LocationClientTypes.GeofenceGeometry? = nil
        )
        {
            self.geofenceId = geofenceId
            self.geometry = geometry
        }
    }

}
