// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension LocationClientTypes {
    /// Contains a search result from a position search query that is run on a place index resource.
    public struct SearchForPositionResult: Swift.Equatable {
        /// The distance in meters of a great-circle arc between the query position and the result. A great-circle arc is the shortest path on a sphere, in this case the Earth. This returns the shortest distance between two locations.
        /// This member is required.
        public var distance: Swift.Double?
        /// Details about the search result, such as its address and position.
        /// This member is required.
        public var place: LocationClientTypes.Place?

        public init (
            distance: Swift.Double? = nil,
            place: LocationClientTypes.Place? = nil
        )
        {
            self.distance = distance
            self.place = place
        }
    }

}
