// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct UpdateTrackerInput: Swift.Equatable {
    /// Updates the description for the tracker resource.
    public var description: Swift.String?
    /// Updates the position filtering for the tracker resource. Valid values:
    ///
    /// * TimeBased - Location updates are evaluated against linked geofence collections, but not every location update is stored. If your update frequency is more often than 30 seconds, only one update per 30 seconds is stored for each unique device ID.
    ///
    /// * DistanceBased - If the device has moved less than 30 m (98.4 ft), location updates are ignored. Location updates within this distance are neither evaluated against linked geofence collections, nor stored. This helps control costs by reducing the number of geofence evaluations and historical device positions to paginate through. Distance-based filtering can also reduce the effects of GPS noise when displaying device trajectories on a map.
    ///
    /// * AccuracyBased - If the device has moved less than the measured accuracy, location updates are ignored. For example, if two consecutive updates from a device have a horizontal accuracy of 5 m and 10 m, the second update is ignored if the device has moved less than 15 m. Ignored location updates are neither evaluated against linked geofence collections, nor stored. This helps educe the effects of GPS noise when displaying device trajectories on a map, and can help control costs by reducing the number of geofence evaluations.
    public var positionFiltering: LocationClientTypes.PositionFiltering?
    /// Updates the pricing plan for the tracker resource. For more information about each pricing plan option restrictions, see [Amazon Location Service pricing](https://aws.amazon.com/location/pricing/).
    public var pricingPlan: LocationClientTypes.PricingPlan?
    /// Updates the data provider for the tracker resource. A required value for the following pricing plans: MobileAssetTracking| MobileAssetManagement For more information about [data providers](https://aws.amazon.com/location/data-providers/) and [pricing plans](https://aws.amazon.com/location/pricing/), see the Amazon Location Service product page This can only be updated when updating the PricingPlan in the same request. Amazon Location Service uses PricingPlanDataSource to calculate billing for your tracker resource. Your data won't be shared with the data provider, and will remain in your AWS account and Region unless you move it.
    public var pricingPlanDataSource: Swift.String?
    /// The name of the tracker resource to update.
    /// This member is required.
    public var trackerName: Swift.String?

    public init (
        description: Swift.String? = nil,
        positionFiltering: LocationClientTypes.PositionFiltering? = nil,
        pricingPlan: LocationClientTypes.PricingPlan? = nil,
        pricingPlanDataSource: Swift.String? = nil,
        trackerName: Swift.String? = nil
    )
    {
        self.description = description
        self.positionFiltering = positionFiltering
        self.pricingPlan = pricingPlan
        self.pricingPlanDataSource = pricingPlanDataSource
        self.trackerName = trackerName
    }
}
