// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension NimbleClientTypes {
    ///
    public struct LaunchProfileInitializationScript: Swift.Equatable {
        /// The initialization script.
        public var script: Swift.String?
        /// The unique identifier for a studio component resource.
        public var studioComponentId: Swift.String?
        /// The name for the studio component.
        public var studioComponentName: Swift.String?

        public init (
            script: Swift.String? = nil,
            studioComponentId: Swift.String? = nil,
            studioComponentName: Swift.String? = nil
        )
        {
            self.script = script
            self.studioComponentId = studioComponentId
            self.studioComponentName = studioComponentName
        }
    }

}
