// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetExperimentResultsOutputResponse: Swift.Equatable {
    /// An array of structures that include the reports that you requested.
    public var reports: [EvidentlyClientTypes.ExperimentReport]?
    /// An array of structures that include experiment results including metric names and values.
    public var resultsData: [EvidentlyClientTypes.ExperimentResultsData]?
    /// The timestamps of each result returned.
    public var timestamps: [ClientRuntime.Date]?

    public init (
        reports: [EvidentlyClientTypes.ExperimentReport]? = nil,
        resultsData: [EvidentlyClientTypes.ExperimentResultsData]? = nil,
        timestamps: [ClientRuntime.Date]? = nil
    )
    {
        self.reports = reports
        self.resultsData = resultsData
        self.timestamps = timestamps
    }
}
