// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetStatisticsInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case aggregationField
        case indexName
        case queryString
        case queryVersion
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let aggregationField = aggregationField {
            try encodeContainer.encode(aggregationField, forKey: .aggregationField)
        }
        if let indexName = indexName {
            try encodeContainer.encode(indexName, forKey: .indexName)
        }
        if let queryString = queryString {
            try encodeContainer.encode(queryString, forKey: .queryString)
        }
        if let queryVersion = queryVersion {
            try encodeContainer.encode(queryVersion, forKey: .queryVersion)
        }
    }
}
