// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DetectTextInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case filters = "Filters"
        case image = "Image"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let filters = filters {
            try encodeContainer.encode(filters, forKey: .filters)
        }
        if let image = image {
            try encodeContainer.encode(image, forKey: .image)
        }
    }
}
