// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DetectModerationLabelsInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case humanLoopConfig = "HumanLoopConfig"
        case image = "Image"
        case minConfidence = "MinConfidence"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let humanLoopConfig = humanLoopConfig {
            try encodeContainer.encode(humanLoopConfig, forKey: .humanLoopConfig)
        }
        if let image = image {
            try encodeContainer.encode(image, forKey: .image)
        }
        if let minConfidence = minConfidence {
            try encodeContainer.encode(minConfidence, forKey: .minConfidence)
        }
    }
}
