// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension ListDatasetEntriesInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case containsLabels = "ContainsLabels"
        case datasetArn = "DatasetArn"
        case hasErrors = "HasErrors"
        case labeled = "Labeled"
        case maxResults = "MaxResults"
        case nextToken = "NextToken"
        case sourceRefContains = "SourceRefContains"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let containsLabels = containsLabels {
            var containsLabelsContainer = encodeContainer.nestedUnkeyedContainer(forKey: .containsLabels)
            for datasetlabels0 in containsLabels {
                try containsLabelsContainer.encode(datasetlabels0)
            }
        }
        if let datasetArn = datasetArn {
            try encodeContainer.encode(datasetArn, forKey: .datasetArn)
        }
        if let hasErrors = hasErrors {
            try encodeContainer.encode(hasErrors, forKey: .hasErrors)
        }
        if let labeled = labeled {
            try encodeContainer.encode(labeled, forKey: .labeled)
        }
        if let maxResults = maxResults {
            try encodeContainer.encode(maxResults, forKey: .maxResults)
        }
        if let nextToken = nextToken {
            try encodeContainer.encode(nextToken, forKey: .nextToken)
        }
        if let sourceRefContains = sourceRefContains {
            try encodeContainer.encode(sourceRefContains, forKey: .sourceRefContains)
        }
    }
}
