// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension PinpointClientTypes.ImportJobResponse: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case applicationId = "ApplicationId"
        case completedPieces = "CompletedPieces"
        case completionDate = "CompletionDate"
        case creationDate = "CreationDate"
        case definition = "Definition"
        case failedPieces = "FailedPieces"
        case failures = "Failures"
        case id = "Id"
        case jobStatus = "JobStatus"
        case totalFailures = "TotalFailures"
        case totalPieces = "TotalPieces"
        case totalProcessed = "TotalProcessed"
        case type = "Type"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let applicationId = applicationId {
            try encodeContainer.encode(applicationId, forKey: .applicationId)
        }
        if let completedPieces = completedPieces {
            try encodeContainer.encode(completedPieces, forKey: .completedPieces)
        }
        if let completionDate = completionDate {
            try encodeContainer.encode(completionDate, forKey: .completionDate)
        }
        if let creationDate = creationDate {
            try encodeContainer.encode(creationDate, forKey: .creationDate)
        }
        if let definition = definition {
            try encodeContainer.encode(definition, forKey: .definition)
        }
        if let failedPieces = failedPieces {
            try encodeContainer.encode(failedPieces, forKey: .failedPieces)
        }
        if let failures = failures {
            var failuresContainer = encodeContainer.nestedUnkeyedContainer(forKey: .failures)
            for listof__string0 in failures {
                try failuresContainer.encode(listof__string0)
            }
        }
        if let id = id {
            try encodeContainer.encode(id, forKey: .id)
        }
        if let jobStatus = jobStatus {
            try encodeContainer.encode(jobStatus.rawValue, forKey: .jobStatus)
        }
        if let totalFailures = totalFailures {
            try encodeContainer.encode(totalFailures, forKey: .totalFailures)
        }
        if let totalPieces = totalPieces {
            try encodeContainer.encode(totalPieces, forKey: .totalPieces)
        }
        if let totalProcessed = totalProcessed {
            try encodeContainer.encode(totalProcessed, forKey: .totalProcessed)
        }
        if let type = type {
            try encodeContainer.encode(type, forKey: .type)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let applicationIdDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .applicationId)
        applicationId = applicationIdDecoded
        let completedPiecesDecoded = try containerValues.decodeIfPresent(Swift.Int.self, forKey: .completedPieces)
        completedPieces = completedPiecesDecoded
        let completionDateDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .completionDate)
        completionDate = completionDateDecoded
        let creationDateDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .creationDate)
        creationDate = creationDateDecoded
        let definitionDecoded = try containerValues.decodeIfPresent(PinpointClientTypes.ImportJobResource.self, forKey: .definition)
        definition = definitionDecoded
        let failedPiecesDecoded = try containerValues.decodeIfPresent(Swift.Int.self, forKey: .failedPieces)
        failedPieces = failedPiecesDecoded
        let failuresContainer = try containerValues.decodeIfPresent([Swift.String?].self, forKey: .failures)
        var failuresDecoded0:[Swift.String]? = nil
        if let failuresContainer = failuresContainer {
            failuresDecoded0 = [Swift.String]()
            for string0 in failuresContainer {
                if let string0 = string0 {
                    failuresDecoded0?.append(string0)
                }
            }
        }
        failures = failuresDecoded0
        let idDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .id)
        id = idDecoded
        let jobStatusDecoded = try containerValues.decodeIfPresent(PinpointClientTypes.JobStatus.self, forKey: .jobStatus)
        jobStatus = jobStatusDecoded
        let totalFailuresDecoded = try containerValues.decodeIfPresent(Swift.Int.self, forKey: .totalFailures)
        totalFailures = totalFailuresDecoded
        let totalPiecesDecoded = try containerValues.decodeIfPresent(Swift.Int.self, forKey: .totalPieces)
        totalPieces = totalPiecesDecoded
        let totalProcessedDecoded = try containerValues.decodeIfPresent(Swift.Int.self, forKey: .totalProcessed)
        totalProcessed = totalProcessedDecoded
        let typeDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .type)
        type = typeDecoded
    }
}
