// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DetectiveClientTypes {
    /// A behavior graph in Detective.
    public struct Graph: Swift.Equatable {
        /// The ARN of the behavior graph.
        public var arn: Swift.String?
        /// The date and time that the behavior graph was created. The value is in milliseconds since the epoch.
        public var createdTime: ClientRuntime.Date?

        public init (
            arn: Swift.String? = nil,
            createdTime: ClientRuntime.Date? = nil
        )
        {
            self.arn = arn
            self.createdTime = createdTime
        }
    }

}
