// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct UpdateRoutingControlStatesInputBody: Swift.Equatable {
    let updateRoutingControlStateEntries: [Route53RecoveryClusterClientTypes.UpdateRoutingControlStateEntry]?
}

extension UpdateRoutingControlStatesInputBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case updateRoutingControlStateEntries = "UpdateRoutingControlStateEntries"
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let updateRoutingControlStateEntriesContainer = try containerValues.decodeIfPresent([Route53RecoveryClusterClientTypes.UpdateRoutingControlStateEntry?].self, forKey: .updateRoutingControlStateEntries)
        var updateRoutingControlStateEntriesDecoded0:[Route53RecoveryClusterClientTypes.UpdateRoutingControlStateEntry]? = nil
        if let updateRoutingControlStateEntriesContainer = updateRoutingControlStateEntriesContainer {
            updateRoutingControlStateEntriesDecoded0 = [Route53RecoveryClusterClientTypes.UpdateRoutingControlStateEntry]()
            for structure0 in updateRoutingControlStateEntriesContainer {
                if let structure0 = structure0 {
                    updateRoutingControlStateEntriesDecoded0?.append(structure0)
                }
            }
        }
        updateRoutingControlStateEntries = updateRoutingControlStateEntriesDecoded0
    }
}
