// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetRecommendationsOutputResponse: Swift.Equatable {
    /// The recommendations.
    /// This member is required.
    public var recommendations: [WisdomClientTypes.RecommendationData]?

    public init (
        recommendations: [WisdomClientTypes.RecommendationData]? = nil
    )
    {
        self.recommendations = recommendations
    }
}
