// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct EnableMetricsCollectionInput: Swift.Equatable {
    /// The name of the Auto Scaling group.
    /// This member is required.
    public var autoScalingGroupName: Swift.String?
    /// The granularity to associate with the metrics to collect. The only valid value is 1Minute.
    /// This member is required.
    public var granularity: Swift.String?
    /// Specifies which group-level metrics to start collecting. You can specify one or more of the following metrics:
    ///
    /// * GroupMinSize
    ///
    /// * GroupMaxSize
    ///
    /// * GroupDesiredCapacity
    ///
    /// * GroupInServiceInstances
    ///
    /// * GroupPendingInstances
    ///
    /// * GroupStandbyInstances
    ///
    /// * GroupTerminatingInstances
    ///
    /// * GroupTotalInstances
    ///
    ///
    /// The instance weighting feature supports the following additional metrics:
    ///
    /// * GroupInServiceCapacity
    ///
    /// * GroupPendingCapacity
    ///
    /// * GroupStandbyCapacity
    ///
    /// * GroupTerminatingCapacity
    ///
    /// * GroupTotalCapacity
    ///
    ///
    /// The warm pools feature supports the following additional metrics:
    ///
    /// * WarmPoolDesiredCapacity
    ///
    /// * WarmPoolWarmedCapacity
    ///
    /// * WarmPoolPendingCapacity
    ///
    /// * WarmPoolTerminatingCapacity
    ///
    /// * WarmPoolTotalCapacity
    ///
    /// * GroupAndWarmPoolDesiredCapacity
    ///
    /// * GroupAndWarmPoolTotalCapacity
    ///
    ///
    /// If you omit this parameter, all metrics are enabled.
    public var metrics: [Swift.String]?

    public init (
        autoScalingGroupName: Swift.String? = nil,
        granularity: Swift.String? = nil,
        metrics: [Swift.String]? = nil
    )
    {
        self.autoScalingGroupName = autoScalingGroupName
        self.granularity = granularity
        self.metrics = metrics
    }
}
