// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct DescribeFraudsterInputBody: Swift.Equatable {
}

extension DescribeFraudsterInputBody: Swift.Decodable {

    public init (from decoder: Swift.Decoder) throws {
    }
}
