// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension VoiceIdClientTypes {
    /// The configuration containing information about the customer-managed KMS Key used for encrypting customer data.
    public struct ServerSideEncryptionConfiguration: Swift.Equatable {
        /// The identifier of the KMS Key you want Voice ID to use to encrypt your data.
        /// This member is required.
        public var kmsKeyId: Swift.String?

        public init (
            kmsKeyId: Swift.String? = nil
        )
        {
            self.kmsKeyId = kmsKeyId
        }
    }

}
