// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct CreateVocabularyInput: Swift.Equatable {
    /// The language code of the vocabulary entries. For a list of languages and their corresponding language codes, see [transcribe-whatis].
    /// This member is required.
    public var languageCode: TranscribeClientTypes.LanguageCode?
    /// An array of strings that contains the vocabulary entries.
    public var phrases: [Swift.String]?
    /// Adds one or more tags, each in the form of a key:value pair, to a new Amazon Transcribe vocabulary at the time you create this new vocabulary.
    public var tags: [TranscribeClientTypes.Tag]?
    /// The S3 location of the text file that contains the definition of the custom vocabulary. The URI must be in the same region as the API endpoint that you are calling. The general form is: For more information about S3 object names, see [Object Keys](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys) in the Amazon S3 Developer Guide. For more information about custom vocabularies, see [Custom vocabularies](https://docs.aws.amazon.com/transcribe/latest/dg/how-vocabulary).
    public var vocabularyFileUri: Swift.String?
    /// The name of the vocabulary. The name must be unique within an Amazon Web Services account. The name is case sensitive. If you try to create a vocabulary with the same name as a previous vocabulary you will receive a ConflictException error.
    /// This member is required.
    public var vocabularyName: Swift.String?

    public init (
        languageCode: TranscribeClientTypes.LanguageCode? = nil,
        phrases: [Swift.String]? = nil,
        tags: [TranscribeClientTypes.Tag]? = nil,
        vocabularyFileUri: Swift.String? = nil,
        vocabularyName: Swift.String? = nil
    )
    {
        self.languageCode = languageCode
        self.phrases = phrases
        self.tags = tags
        self.vocabularyFileUri = vocabularyFileUri
        self.vocabularyName = vocabularyName
    }
}
