// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetCallAnalyticsJobOutputResponse: Swift.Equatable {
    /// An object that contains the results of your call analytics job.
    public var callAnalyticsJob: TranscribeClientTypes.CallAnalyticsJob?

    public init (
        callAnalyticsJob: TranscribeClientTypes.CallAnalyticsJob? = nil
    )
    {
        self.callAnalyticsJob = callAnalyticsJob
    }
}
