// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SsoAdminClientTypes {
    /// The value used for mapping a specified attribute to an identity source.
    public struct AccessControlAttributeValue: Swift.Equatable {
        /// The identity source to use when mapping a specified attribute to Amazon Web Services SSO.
        /// This member is required.
        public var source: [Swift.String]?

        public init (
            source: [Swift.String]? = nil
        )
        {
            self.source = source
        }
    }

}
