// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension PanoramaClientTypes {
    /// The network status of a device.
    public struct NetworkStatus: Swift.Equatable {
        /// The status of Ethernet port 0.
        public var ethernet0Status: PanoramaClientTypes.EthernetStatus?
        /// The status of Ethernet port 1.
        public var ethernet1Status: PanoramaClientTypes.EthernetStatus?

        public init (
            ethernet0Status: PanoramaClientTypes.EthernetStatus? = nil,
            ethernet1Status: PanoramaClientTypes.EthernetStatus? = nil
        )
        {
            self.ethernet0Status = ethernet0Status
            self.ethernet1Status = ethernet1Status
        }
    }

}
