// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension KendraClientTypes {
    /// Provides configuration information for crawling service catalog items in the ServiceNow site
    public struct ServiceNowServiceCatalogConfiguration: Swift.Equatable {
        /// Indicates whether Amazon Kendra should crawl attachments to the service catalog items.
        public var crawlAttachments: Swift.Bool
        /// The name of the ServiceNow field that is mapped to the index document contents field in the Amazon Kendra index.
        /// This member is required.
        public var documentDataFieldName: Swift.String?
        /// The name of the ServiceNow field that is mapped to the index document title field.
        public var documentTitleFieldName: Swift.String?
        /// A list of regular expression patterns. Documents that match the patterns are excluded from the index. Documents that don't match the patterns are included in the index. If a document matches both an exclusion pattern and an inclusion pattern, the document is not included in the index. The regex is applied to the file name of the attachment.
        public var excludeAttachmentFilePatterns: [Swift.String]?
        /// Mapping between ServiceNow fields and Amazon Kendra index fields. You must create the index field before you map the field.
        public var fieldMappings: [KendraClientTypes.DataSourceToIndexFieldMapping]?
        /// A list of regular expression patterns. Documents that match the patterns are included in the index. Documents that don't match the patterns are excluded from the index. If a document matches both an exclusion pattern and an inclusion pattern, the document is not included in the index. The regex is applied to the file name of the attachment.
        public var includeAttachmentFilePatterns: [Swift.String]?

        public init (
            crawlAttachments: Swift.Bool = false,
            documentDataFieldName: Swift.String? = nil,
            documentTitleFieldName: Swift.String? = nil,
            excludeAttachmentFilePatterns: [Swift.String]? = nil,
            fieldMappings: [KendraClientTypes.DataSourceToIndexFieldMapping]? = nil,
            includeAttachmentFilePatterns: [Swift.String]? = nil
        )
        {
            self.crawlAttachments = crawlAttachments
            self.documentDataFieldName = documentDataFieldName
            self.documentTitleFieldName = documentTitleFieldName
            self.excludeAttachmentFilePatterns = excludeAttachmentFilePatterns
            self.fieldMappings = fieldMappings
            self.includeAttachmentFilePatterns = includeAttachmentFilePatterns
        }
    }

}
