// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension Macie2ClientTypes {
    /// Provides information about a sensitive data finding, including the classification job that produced the finding.
    public struct ClassificationDetails: Swift.Equatable {
        /// The path to the folder or file (in Amazon S3) that contains the corresponding sensitive data discovery result for the finding. If a finding applies to a large archive or compressed file, this value is the path to a folder. Otherwise, this value is the path to a file.
        public var detailedResultsLocation: Swift.String?
        /// The Amazon Resource Name (ARN) of the classification job that produced the finding.
        public var jobArn: Swift.String?
        /// The unique identifier for the classification job that produced the finding.
        public var jobId: Swift.String?
        /// The status and other details of the finding.
        public var result: Macie2ClientTypes.ClassificationResult?

        public init (
            detailedResultsLocation: Swift.String? = nil,
            jobArn: Swift.String? = nil,
            jobId: Swift.String? = nil,
            result: Macie2ClientTypes.ClassificationResult? = nil
        )
        {
            self.detailedResultsLocation = detailedResultsLocation
            self.jobArn = jobArn
            self.jobId = jobId
            self.result = result
        }
    }

}
