// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension Macie2ClientTypes.JobDetails: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case isDefinedInJob = "isDefinedInJob"
        case isMonitoredByJob = "isMonitoredByJob"
        case lastJobId = "lastJobId"
        case lastJobRunTime = "lastJobRunTime"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let isDefinedInJob = isDefinedInJob {
            try encodeContainer.encode(isDefinedInJob.rawValue, forKey: .isDefinedInJob)
        }
        if let isMonitoredByJob = isMonitoredByJob {
            try encodeContainer.encode(isMonitoredByJob.rawValue, forKey: .isMonitoredByJob)
        }
        if let lastJobId = lastJobId {
            try encodeContainer.encode(lastJobId, forKey: .lastJobId)
        }
        if let lastJobRunTime = lastJobRunTime {
            try encodeContainer.encode(lastJobRunTime.timeIntervalSince1970, forKey: .lastJobRunTime)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let isDefinedInJobDecoded = try containerValues.decodeIfPresent(Macie2ClientTypes.IsDefinedInJob.self, forKey: .isDefinedInJob)
        isDefinedInJob = isDefinedInJobDecoded
        let isMonitoredByJobDecoded = try containerValues.decodeIfPresent(Macie2ClientTypes.IsMonitoredByJob.self, forKey: .isMonitoredByJob)
        isMonitoredByJob = isMonitoredByJobDecoded
        let lastJobIdDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .lastJobId)
        lastJobId = lastJobIdDecoded
        let lastJobRunTimeDecoded = try containerValues.decodeIfPresent(ClientRuntime.Date.self, forKey: .lastJobRunTime)
        lastJobRunTime = lastJobRunTimeDecoded
    }
}
