// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

/// A snapshot of the documentation of an API. Publishing API documentation involves creating a documentation version associated with an API stage and exporting the versioned documentation to an external (e.g., OpenAPI) file. [Documenting an API](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-documenting-api.html), [DocumentationPart], [DocumentationVersions]
public struct CreateDocumentationVersionOutputResponse: Swift.Equatable {
    /// The date when the API documentation snapshot is created.
    public var createdDate: ClientRuntime.Date?
    /// The description of the API documentation snapshot.
    public var description: Swift.String?
    /// The version identifier of the API documentation snapshot.
    public var version: Swift.String?

    public init (
        createdDate: ClientRuntime.Date? = nil,
        description: Swift.String? = nil,
        version: Swift.String? = nil
    )
    {
        self.createdDate = createdDate
        self.description = description
        self.version = version
    }
}
