// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Deletes an existing documentation version of an API.
public struct DeleteDocumentationVersionInput: Swift.Equatable {
    /// [Required] The version identifier of a to-be-deleted documentation snapshot.
    /// This member is required.
    public var documentationVersion: Swift.String?
    /// [Required] The string identifier of the associated [RestApi].
    /// This member is required.
    public var restApiId: Swift.String?

    public init (
        documentationVersion: Swift.String? = nil,
        restApiId: Swift.String? = nil
    )
    {
        self.documentationVersion = documentationVersion
        self.restApiId = restApiId
    }
}
