// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Represents a collection of [ClientCertificate] resources. [Use Client-Side Certificate](https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-client-side-ssl-authentication.html)
public struct GetClientCertificatesOutputResponse: Swift.Equatable {
    /// The current page of elements from this collection.
    public var items: [ApiGatewayClientTypes.ClientCertificate]?
    /// The current pagination position in the paged result set.
    public var position: Swift.String?

    public init (
        items: [ApiGatewayClientTypes.ClientCertificate]? = nil,
        position: Swift.String? = nil
    )
    {
        self.items = items
        self.position = position
    }
}
