// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// A list of [Stage] resources that are associated with the [ApiKey] resource. [Deploying API in Stages](https://docs.aws.amazon.com/apigateway/latest/developerguide/stages.html)
public struct GetStagesOutputResponse: Swift.Equatable {
    /// The current page of elements from this collection.
    public var item: [ApiGatewayClientTypes.Stage]?

    public init (
        item: [ApiGatewayClientTypes.Stage]? = nil
    )
    {
        self.item = item
    }
}
