// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension ApiGatewayClientTypes.ThrottleSettings: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case burstLimit
        case rateLimit
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if burstLimit != 0 {
            try encodeContainer.encode(burstLimit, forKey: .burstLimit)
        }
        if rateLimit != 0.0 {
            try encodeContainer.encode(rateLimit, forKey: .rateLimit)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let burstLimitDecoded = try containerValues.decode(Swift.Int.self, forKey: .burstLimit)
        burstLimit = burstLimitDecoded
        let rateLimitDecoded = try containerValues.decode(Swift.Double.self, forKey: .rateLimit)
        rateLimit = rateLimitDecoded
    }
}
