// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Request to update an existing [Method] resource.
public struct UpdateMethodInput: Swift.Equatable {
    /// [Required] The HTTP verb of the [Method] resource.
    /// This member is required.
    public var httpMethod: Swift.String?
    /// A list of update operations to be applied to the specified resource and in the order specified in this list.
    public var patchOperations: [ApiGatewayClientTypes.PatchOperation]?
    /// [Required] The [Resource] identifier for the [Method] resource.
    /// This member is required.
    public var resourceId: Swift.String?
    /// [Required] The string identifier of the associated [RestApi].
    /// This member is required.
    public var restApiId: Swift.String?

    public init (
        httpMethod: Swift.String? = nil,
        patchOperations: [ApiGatewayClientTypes.PatchOperation]? = nil,
        resourceId: Swift.String? = nil,
        restApiId: Swift.String? = nil
    )
    {
        self.httpMethod = httpMethod
        self.patchOperations = patchOperations
        self.resourceId = resourceId
        self.restApiId = restApiId
    }
}
