// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension AutoScalingPlansClientTypes.ScalingInstruction: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case customizedLoadMetricSpecification = "CustomizedLoadMetricSpecification"
        case disableDynamicScaling = "DisableDynamicScaling"
        case maxCapacity = "MaxCapacity"
        case minCapacity = "MinCapacity"
        case predefinedLoadMetricSpecification = "PredefinedLoadMetricSpecification"
        case predictiveScalingMaxCapacityBehavior = "PredictiveScalingMaxCapacityBehavior"
        case predictiveScalingMaxCapacityBuffer = "PredictiveScalingMaxCapacityBuffer"
        case predictiveScalingMode = "PredictiveScalingMode"
        case resourceId = "ResourceId"
        case scalableDimension = "ScalableDimension"
        case scalingPolicyUpdateBehavior = "ScalingPolicyUpdateBehavior"
        case scheduledActionBufferTime = "ScheduledActionBufferTime"
        case serviceNamespace = "ServiceNamespace"
        case targetTrackingConfigurations = "TargetTrackingConfigurations"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let customizedLoadMetricSpecification = customizedLoadMetricSpecification {
            try encodeContainer.encode(customizedLoadMetricSpecification, forKey: .customizedLoadMetricSpecification)
        }
        if let disableDynamicScaling = disableDynamicScaling {
            try encodeContainer.encode(disableDynamicScaling, forKey: .disableDynamicScaling)
        }
        if let maxCapacity = maxCapacity {
            try encodeContainer.encode(maxCapacity, forKey: .maxCapacity)
        }
        if let minCapacity = minCapacity {
            try encodeContainer.encode(minCapacity, forKey: .minCapacity)
        }
        if let predefinedLoadMetricSpecification = predefinedLoadMetricSpecification {
            try encodeContainer.encode(predefinedLoadMetricSpecification, forKey: .predefinedLoadMetricSpecification)
        }
        if let predictiveScalingMaxCapacityBehavior = predictiveScalingMaxCapacityBehavior {
            try encodeContainer.encode(predictiveScalingMaxCapacityBehavior.rawValue, forKey: .predictiveScalingMaxCapacityBehavior)
        }
        if let predictiveScalingMaxCapacityBuffer = predictiveScalingMaxCapacityBuffer {
            try encodeContainer.encode(predictiveScalingMaxCapacityBuffer, forKey: .predictiveScalingMaxCapacityBuffer)
        }
        if let predictiveScalingMode = predictiveScalingMode {
            try encodeContainer.encode(predictiveScalingMode.rawValue, forKey: .predictiveScalingMode)
        }
        if let resourceId = resourceId {
            try encodeContainer.encode(resourceId, forKey: .resourceId)
        }
        if let scalableDimension = scalableDimension {
            try encodeContainer.encode(scalableDimension.rawValue, forKey: .scalableDimension)
        }
        if let scalingPolicyUpdateBehavior = scalingPolicyUpdateBehavior {
            try encodeContainer.encode(scalingPolicyUpdateBehavior.rawValue, forKey: .scalingPolicyUpdateBehavior)
        }
        if let scheduledActionBufferTime = scheduledActionBufferTime {
            try encodeContainer.encode(scheduledActionBufferTime, forKey: .scheduledActionBufferTime)
        }
        if let serviceNamespace = serviceNamespace {
            try encodeContainer.encode(serviceNamespace.rawValue, forKey: .serviceNamespace)
        }
        if let targetTrackingConfigurations = targetTrackingConfigurations {
            var targetTrackingConfigurationsContainer = encodeContainer.nestedUnkeyedContainer(forKey: .targetTrackingConfigurations)
            for targettrackingconfigurations0 in targetTrackingConfigurations {
                try targetTrackingConfigurationsContainer.encode(targettrackingconfigurations0)
            }
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let serviceNamespaceDecoded = try containerValues.decodeIfPresent(AutoScalingPlansClientTypes.ServiceNamespace.self, forKey: .serviceNamespace)
        serviceNamespace = serviceNamespaceDecoded
        let resourceIdDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .resourceId)
        resourceId = resourceIdDecoded
        let scalableDimensionDecoded = try containerValues.decodeIfPresent(AutoScalingPlansClientTypes.ScalableDimension.self, forKey: .scalableDimension)
        scalableDimension = scalableDimensionDecoded
        let minCapacityDecoded = try containerValues.decodeIfPresent(Swift.Int.self, forKey: .minCapacity)
        minCapacity = minCapacityDecoded
        let maxCapacityDecoded = try containerValues.decodeIfPresent(Swift.Int.self, forKey: .maxCapacity)
        maxCapacity = maxCapacityDecoded
        let targetTrackingConfigurationsContainer = try containerValues.decodeIfPresent([AutoScalingPlansClientTypes.TargetTrackingConfiguration?].self, forKey: .targetTrackingConfigurations)
        var targetTrackingConfigurationsDecoded0:[AutoScalingPlansClientTypes.TargetTrackingConfiguration]? = nil
        if let targetTrackingConfigurationsContainer = targetTrackingConfigurationsContainer {
            targetTrackingConfigurationsDecoded0 = [AutoScalingPlansClientTypes.TargetTrackingConfiguration]()
            for structure0 in targetTrackingConfigurationsContainer {
                if let structure0 = structure0 {
                    targetTrackingConfigurationsDecoded0?.append(structure0)
                }
            }
        }
        targetTrackingConfigurations = targetTrackingConfigurationsDecoded0
        let predefinedLoadMetricSpecificationDecoded = try containerValues.decodeIfPresent(AutoScalingPlansClientTypes.PredefinedLoadMetricSpecification.self, forKey: .predefinedLoadMetricSpecification)
        predefinedLoadMetricSpecification = predefinedLoadMetricSpecificationDecoded
        let customizedLoadMetricSpecificationDecoded = try containerValues.decodeIfPresent(AutoScalingPlansClientTypes.CustomizedLoadMetricSpecification.self, forKey: .customizedLoadMetricSpecification)
        customizedLoadMetricSpecification = customizedLoadMetricSpecificationDecoded
        let scheduledActionBufferTimeDecoded = try containerValues.decodeIfPresent(Swift.Int.self, forKey: .scheduledActionBufferTime)
        scheduledActionBufferTime = scheduledActionBufferTimeDecoded
        let predictiveScalingMaxCapacityBehaviorDecoded = try containerValues.decodeIfPresent(AutoScalingPlansClientTypes.PredictiveScalingMaxCapacityBehavior.self, forKey: .predictiveScalingMaxCapacityBehavior)
        predictiveScalingMaxCapacityBehavior = predictiveScalingMaxCapacityBehaviorDecoded
        let predictiveScalingMaxCapacityBufferDecoded = try containerValues.decodeIfPresent(Swift.Int.self, forKey: .predictiveScalingMaxCapacityBuffer)
        predictiveScalingMaxCapacityBuffer = predictiveScalingMaxCapacityBufferDecoded
        let predictiveScalingModeDecoded = try containerValues.decodeIfPresent(AutoScalingPlansClientTypes.PredictiveScalingMode.self, forKey: .predictiveScalingMode)
        predictiveScalingMode = predictiveScalingModeDecoded
        let scalingPolicyUpdateBehaviorDecoded = try containerValues.decodeIfPresent(AutoScalingPlansClientTypes.ScalingPolicyUpdateBehavior.self, forKey: .scalingPolicyUpdateBehavior)
        scalingPolicyUpdateBehavior = scalingPolicyUpdateBehaviorDecoded
        let disableDynamicScalingDecoded = try containerValues.decodeIfPresent(Swift.Bool.self, forKey: .disableDynamicScaling)
        disableDynamicScaling = disableDynamicScalingDecoded
    }
}
