// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct CreateEnvironmentAccountConnectionInput: Swift.Equatable {
    /// When included, if two identical requests are made with the same client token, Proton returns the environment account connection that the first request created.
    public var clientToken: Swift.String?
    /// The name of the Proton environment that's created in the associated management account.
    /// This member is required.
    public var environmentName: Swift.String?
    /// The ID of the management account that accepts or rejects the environment account connection. You create an manage the Proton environment in this account. If the management account accepts the environment account connection, Proton can use the associated IAM role to provision environment infrastructure resources in the associated environment account.
    /// This member is required.
    public var managementAccountId: Swift.String?
    /// The Amazon Resource Name (ARN) of the IAM service role that's created in the environment account. Proton uses this role to provision infrastructure resources in the associated environment account.
    /// This member is required.
    public var roleArn: Swift.String?
    /// Tags for your environment account connection. For more information, see [Proton resources and tagging](https://docs.aws.amazon.com/proton/latest/adminguide/resources.html) in the Proton Administrator Guide.
    public var tags: [ProtonClientTypes.Tag]?

    public init (
        clientToken: Swift.String? = nil,
        environmentName: Swift.String? = nil,
        managementAccountId: Swift.String? = nil,
        roleArn: Swift.String? = nil,
        tags: [ProtonClientTypes.Tag]? = nil
    )
    {
        self.clientToken = clientToken
        self.environmentName = environmentName
        self.managementAccountId = managementAccountId
        self.roleArn = roleArn
        self.tags = tags
    }
}
