// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DeleteEnvironmentTemplateVersionOutputResponse: Swift.Equatable {
    /// The environment template version detail data that's returned by Proton.
    public var environmentTemplateVersion: ProtonClientTypes.EnvironmentTemplateVersion?

    public init (
        environmentTemplateVersion: ProtonClientTypes.EnvironmentTemplateVersion? = nil
    )
    {
        self.environmentTemplateVersion = environmentTemplateVersion
    }
}
