// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct UpdateEnvironmentAccountConnectionInput: Swift.Equatable {
    /// The ID of the environment account connection to update.
    /// This member is required.
    public var id: Swift.String?
    /// The Amazon Resource Name (ARN) of the IAM service role that is associated with the environment account connection to update.
    /// This member is required.
    public var roleArn: Swift.String?

    public init (
        id: Swift.String? = nil,
        roleArn: Swift.String? = nil
    )
    {
        self.id = id
        self.roleArn = roleArn
    }
}
