// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetMetricStreamOutputResponse: Swift.Equatable {
    /// The ARN of the metric stream.
    public var arn: Swift.String?
    /// The date that the metric stream was created.
    public var creationDate: ClientRuntime.Date?
    /// If this array of metric namespaces is present, then these namespaces are the only metric namespaces that are not streamed by this metric stream. In this case, all other metric namespaces in the account are streamed by this metric stream.
    public var excludeFilters: [CloudWatchClientTypes.MetricStreamFilter]?
    /// The ARN of the Amazon Kinesis Firehose delivery stream that is used by this metric stream.
    public var firehoseArn: Swift.String?
    /// If this array of metric namespaces is present, then these namespaces are the only metric namespaces that are streamed by this metric stream.
    public var includeFilters: [CloudWatchClientTypes.MetricStreamFilter]?
    /// The date of the most recent update to the metric stream's configuration.
    public var lastUpdateDate: ClientRuntime.Date?
    /// The name of the metric stream.
    public var name: Swift.String?
    ///
    public var outputFormat: CloudWatchClientTypes.MetricStreamOutputFormat?
    /// The ARN of the IAM role that is used by this metric stream.
    public var roleArn: Swift.String?
    /// The state of the metric stream. The possible values are running and stopped.
    public var state: Swift.String?

    public init (
        arn: Swift.String? = nil,
        creationDate: ClientRuntime.Date? = nil,
        excludeFilters: [CloudWatchClientTypes.MetricStreamFilter]? = nil,
        firehoseArn: Swift.String? = nil,
        includeFilters: [CloudWatchClientTypes.MetricStreamFilter]? = nil,
        lastUpdateDate: ClientRuntime.Date? = nil,
        name: Swift.String? = nil,
        outputFormat: CloudWatchClientTypes.MetricStreamOutputFormat? = nil,
        roleArn: Swift.String? = nil,
        state: Swift.String? = nil
    )
    {
        self.arn = arn
        self.creationDate = creationDate
        self.excludeFilters = excludeFilters
        self.firehoseArn = firehoseArn
        self.includeFilters = includeFilters
        self.lastUpdateDate = lastUpdateDate
        self.name = name
        self.outputFormat = outputFormat
        self.roleArn = roleArn
        self.state = state
    }
}
