// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ResolveComponentCandidatesInput: Swift.Equatable {
    /// The list of components to resolve.
    /// This member is required.
    public var componentCandidates: [GreengrassV2ClientTypes.ComponentCandidate]?
    /// The platform to use to resolve compatible components.
    /// This member is required.
    public var platform: GreengrassV2ClientTypes.ComponentPlatform?

    public init (
        componentCandidates: [GreengrassV2ClientTypes.ComponentCandidate]? = nil,
        platform: GreengrassV2ClientTypes.ComponentPlatform? = nil
    )
    {
        self.componentCandidates = componentCandidates
        self.platform = platform
    }
}
