// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ContainsPiiEntitiesInput: Swift.Equatable {
    /// The language of the input documents.
    /// This member is required.
    public var languageCode: ComprehendClientTypes.LanguageCode?
    /// Creates a new document classification request to analyze a single document in real-time, returning personally identifiable information (PII) entity labels.
    /// This member is required.
    public var text: Swift.String?

    public init (
        languageCode: ComprehendClientTypes.LanguageCode? = nil,
        text: Swift.String? = nil
    )
    {
        self.languageCode = languageCode
        self.text = text
    }
}
