// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension ComprehendClientTypes {
    /// Describes a key noun phrase.
    public struct KeyPhrase: Swift.Equatable {
        /// A character offset in the input text that shows where the key phrase begins (the first character is at position 0). The offset returns the position of each UTF-8 code point in the string. A code point is the abstract character from a particular graphical representation. For example, a multi-byte UTF-8 character maps to a single code point.
        public var beginOffset: Swift.Int?
        /// A character offset in the input text where the key phrase ends. The offset returns the position of each UTF-8 code point in the string. A code point is the abstract character from a particular graphical representation. For example, a multi-byte UTF-8 character maps to a single code point.
        public var endOffset: Swift.Int?
        /// The level of confidence that Amazon Comprehend has in the accuracy of the detection.
        public var score: Swift.Float?
        /// The text of a key noun phrase.
        public var text: Swift.String?

        public init (
            beginOffset: Swift.Int? = nil,
            endOffset: Swift.Int? = nil,
            score: Swift.Float? = nil,
            text: Swift.String? = nil
        )
        {
            self.beginOffset = beginOffset
            self.endOffset = endOffset
            self.score = score
            self.text = text
        }
    }

}
