// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension UpdateEndpointInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case desiredDataAccessRoleArn = "DesiredDataAccessRoleArn"
        case desiredInferenceUnits = "DesiredInferenceUnits"
        case desiredModelArn = "DesiredModelArn"
        case endpointArn = "EndpointArn"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let desiredDataAccessRoleArn = desiredDataAccessRoleArn {
            try encodeContainer.encode(desiredDataAccessRoleArn, forKey: .desiredDataAccessRoleArn)
        }
        if let desiredInferenceUnits = desiredInferenceUnits {
            try encodeContainer.encode(desiredInferenceUnits, forKey: .desiredInferenceUnits)
        }
        if let desiredModelArn = desiredModelArn {
            try encodeContainer.encode(desiredModelArn, forKey: .desiredModelArn)
        }
        if let endpointArn = endpointArn {
            try encodeContainer.encode(endpointArn, forKey: .endpointArn)
        }
    }
}
