// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetResourceMetricsInput: Swift.Equatable {
    /// The date and time specifying the end of the requested time series data. The value specified is exclusive - data points less than (but not equal to) EndTime will be returned. The value for EndTime must be later than the value for StartTime.
    /// This member is required.
    public var endTime: ClientRuntime.Date?
    /// An immutable, AWS Region-unique identifier for a data source. Performance Insights gathers metrics from this data source. To use a DB instance as a data source, specify its DbiResourceId value. For example, specify db-FAIHNTYBKTGAUSUZQYPDS2GW4A.
    /// This member is required.
    public var identifier: Swift.String?
    /// The maximum number of items to return in the response. If more items exist than the specified MaxRecords value, a pagination token is included in the response so that the remaining results can be retrieved.
    public var maxResults: Swift.Int?
    /// An array of one or more queries to perform. Each query must specify a Performance Insights metric, and can optionally specify aggregation and filtering criteria.
    /// This member is required.
    public var metricQueries: [PiClientTypes.MetricQuery]?
    /// An optional pagination token provided by a previous request. If this parameter is specified, the response includes only records beyond the token, up to the value specified by MaxRecords.
    public var nextToken: Swift.String?
    /// The granularity, in seconds, of the data points returned from Performance Insights. A period can be as short as one second, or as long as one day (86400 seconds). Valid values are:
    ///
    /// * 1 (one second)
    ///
    /// * 60 (one minute)
    ///
    /// * 300 (five minutes)
    ///
    /// * 3600 (one hour)
    ///
    /// * 86400 (twenty-four hours)
    ///
    ///
    /// If you don't specify PeriodInSeconds, then Performance Insights will choose a value for you, with a goal of returning roughly 100-200 data points in the response.
    public var periodInSeconds: Swift.Int?
    /// The AWS service for which Performance Insights returns metrics. The only valid value for ServiceType is RDS.
    /// This member is required.
    public var serviceType: PiClientTypes.ServiceType?
    /// The date and time specifying the beginning of the requested time series data. You can't specify a StartTime that's earlier than 7 days ago. The value specified is inclusive - data points equal to or greater than StartTime will be returned. The value for StartTime must be earlier than the value for EndTime.
    /// This member is required.
    public var startTime: ClientRuntime.Date?

    public init (
        endTime: ClientRuntime.Date? = nil,
        identifier: Swift.String? = nil,
        maxResults: Swift.Int? = nil,
        metricQueries: [PiClientTypes.MetricQuery]? = nil,
        nextToken: Swift.String? = nil,
        periodInSeconds: Swift.Int? = nil,
        serviceType: PiClientTypes.ServiceType? = nil,
        startTime: ClientRuntime.Date? = nil
    )
    {
        self.endTime = endTime
        self.identifier = identifier
        self.maxResults = maxResults
        self.metricQueries = metricQueries
        self.nextToken = nextToken
        self.periodInSeconds = periodInSeconds
        self.serviceType = serviceType
        self.startTime = startTime
    }
}
