// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct UpdateSiteAddressInput: Swift.Equatable {
    /// The address for the site.
    /// This member is required.
    public var address: OutpostsClientTypes.Address?
    /// The type of the address.
    /// This member is required.
    public var addressType: OutpostsClientTypes.AddressType?
    /// The ID or the Amazon Resource Name (ARN) of the site.
    /// This member is required.
    public var siteId: Swift.String?

    public init (
        address: OutpostsClientTypes.Address? = nil,
        addressType: OutpostsClientTypes.AddressType? = nil,
        siteId: Swift.String? = nil
    )
    {
        self.address = address
        self.addressType = addressType
        self.siteId = siteId
    }
}
