// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension DlmClientTypes {
    /// Specifies a backup schedule for a snapshot or AMI lifecycle policy.
    public struct Schedule: Swift.Equatable {
        /// Copy all user-defined tags on a source volume to snapshots of the volume created by this policy.
        public var copyTags: Swift.Bool
        /// The creation rule.
        public var createRule: DlmClientTypes.CreateRule?
        /// The rule for cross-Region snapshot copies. You can only specify cross-Region copy rules for policies that create snapshots in a Region. If the policy creates snapshots on an Outpost, then you cannot copy the snapshots to a Region or to an Outpost. If the policy creates snapshots in a Region, then snapshots can be copied to up to three Regions or Outposts.
        public var crossRegionCopyRules: [DlmClientTypes.CrossRegionCopyRule]?
        /// The AMI deprecation rule for the schedule.
        public var deprecateRule: DlmClientTypes.DeprecateRule?
        /// The rule for enabling fast snapshot restore.
        public var fastRestoreRule: DlmClientTypes.FastRestoreRule?
        /// The name of the schedule.
        public var name: Swift.String?
        /// The retention rule.
        public var retainRule: DlmClientTypes.RetainRule?
        /// The rule for sharing snapshots with other Amazon Web Services accounts.
        public var shareRules: [DlmClientTypes.ShareRule]?
        /// The tags to apply to policy-created resources. These user-defined tags are in addition to the Amazon Web Services-added lifecycle tags.
        public var tagsToAdd: [DlmClientTypes.Tag]?
        /// A collection of key/value pairs with values determined dynamically when the policy is executed. Keys may be any valid Amazon EC2 tag key. Values must be in one of the two following formats: $(instance-id) or $(timestamp). Variable tags are only valid for EBS Snapshot Management – Instance policies.
        public var variableTags: [DlmClientTypes.Tag]?

        public init (
            copyTags: Swift.Bool = false,
            createRule: DlmClientTypes.CreateRule? = nil,
            crossRegionCopyRules: [DlmClientTypes.CrossRegionCopyRule]? = nil,
            deprecateRule: DlmClientTypes.DeprecateRule? = nil,
            fastRestoreRule: DlmClientTypes.FastRestoreRule? = nil,
            name: Swift.String? = nil,
            retainRule: DlmClientTypes.RetainRule? = nil,
            shareRules: [DlmClientTypes.ShareRule]? = nil,
            tagsToAdd: [DlmClientTypes.Tag]? = nil,
            variableTags: [DlmClientTypes.Tag]? = nil
        )
        {
            self.copyTags = copyTags
            self.createRule = createRule
            self.crossRegionCopyRules = crossRegionCopyRules
            self.deprecateRule = deprecateRule
            self.fastRestoreRule = fastRestoreRule
            self.name = name
            self.retainRule = retainRule
            self.shareRules = shareRules
            self.tagsToAdd = tagsToAdd
            self.variableTags = variableTags
        }
    }

}
