// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension CodePipelineClientTypes.ArtifactDetails: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case maximumCount
        case minimumCount
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if maximumCount != 0 {
            try encodeContainer.encode(maximumCount, forKey: .maximumCount)
        }
        if minimumCount != 0 {
            try encodeContainer.encode(minimumCount, forKey: .minimumCount)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let minimumCountDecoded = try containerValues.decode(Swift.Int.self, forKey: .minimumCount)
        minimumCount = minimumCountDecoded
        let maximumCountDecoded = try containerValues.decode(Swift.Int.self, forKey: .maximumCount)
        maximumCount = maximumCountDecoded
    }
}
