// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension SageMakerClientTypes.AutoMLJobConfig: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case completionCriteria = "CompletionCriteria"
        case securityConfig = "SecurityConfig"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let completionCriteria = completionCriteria {
            try encodeContainer.encode(completionCriteria, forKey: .completionCriteria)
        }
        if let securityConfig = securityConfig {
            try encodeContainer.encode(securityConfig, forKey: .securityConfig)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let completionCriteriaDecoded = try containerValues.decodeIfPresent(SageMakerClientTypes.AutoMLJobCompletionCriteria.self, forKey: .completionCriteria)
        completionCriteria = completionCriteriaDecoded
        let securityConfigDecoded = try containerValues.decodeIfPresent(SageMakerClientTypes.AutoMLSecurityConfig.self, forKey: .securityConfig)
        securityConfig = securityConfigDecoded
    }
}
