// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SageMakerClientTypes {
    /// Information about the metric for a candidate produced by an AutoML job.
    public struct MetricDatum: Swift.Equatable {
        /// The name of the metric.
        public var metricName: SageMakerClientTypes.AutoMLMetricEnum?
        /// The dataset split from which the AutoML job produced the metric.
        public var `set`: SageMakerClientTypes.MetricSetSource?
        /// The value of the metric.
        public var value: Swift.Float

        public init (
            metricName: SageMakerClientTypes.AutoMLMetricEnum? = nil,
            `set`: SageMakerClientTypes.MetricSetSource? = nil,
            value: Swift.Float = 0.0
        )
        {
            self.metricName = metricName
            self.`set` = `set`
            self.value = value
        }
    }

}
