// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension SageMakerClientTypes.RecommendationJobInputConfig: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case endpointConfigurations = "EndpointConfigurations"
        case jobDurationInSeconds = "JobDurationInSeconds"
        case modelPackageVersionArn = "ModelPackageVersionArn"
        case resourceLimit = "ResourceLimit"
        case trafficPattern = "TrafficPattern"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let endpointConfigurations = endpointConfigurations {
            var endpointConfigurationsContainer = encodeContainer.nestedUnkeyedContainer(forKey: .endpointConfigurations)
            for endpointinputconfigurations0 in endpointConfigurations {
                try endpointConfigurationsContainer.encode(endpointinputconfigurations0)
            }
        }
        if let jobDurationInSeconds = jobDurationInSeconds {
            try encodeContainer.encode(jobDurationInSeconds, forKey: .jobDurationInSeconds)
        }
        if let modelPackageVersionArn = modelPackageVersionArn {
            try encodeContainer.encode(modelPackageVersionArn, forKey: .modelPackageVersionArn)
        }
        if let resourceLimit = resourceLimit {
            try encodeContainer.encode(resourceLimit, forKey: .resourceLimit)
        }
        if let trafficPattern = trafficPattern {
            try encodeContainer.encode(trafficPattern, forKey: .trafficPattern)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let modelPackageVersionArnDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .modelPackageVersionArn)
        modelPackageVersionArn = modelPackageVersionArnDecoded
        let jobDurationInSecondsDecoded = try containerValues.decodeIfPresent(Swift.Int.self, forKey: .jobDurationInSeconds)
        jobDurationInSeconds = jobDurationInSecondsDecoded
        let trafficPatternDecoded = try containerValues.decodeIfPresent(SageMakerClientTypes.TrafficPattern.self, forKey: .trafficPattern)
        trafficPattern = trafficPatternDecoded
        let resourceLimitDecoded = try containerValues.decodeIfPresent(SageMakerClientTypes.RecommendationJobResourceLimit.self, forKey: .resourceLimit)
        resourceLimit = resourceLimitDecoded
        let endpointConfigurationsContainer = try containerValues.decodeIfPresent([SageMakerClientTypes.EndpointInputConfiguration?].self, forKey: .endpointConfigurations)
        var endpointConfigurationsDecoded0:[SageMakerClientTypes.EndpointInputConfiguration]? = nil
        if let endpointConfigurationsContainer = endpointConfigurationsContainer {
            endpointConfigurationsDecoded0 = [SageMakerClientTypes.EndpointInputConfiguration]()
            for structure0 in endpointConfigurationsContainer {
                if let structure0 = structure0 {
                    endpointConfigurationsDecoded0?.append(structure0)
                }
            }
        }
        endpointConfigurations = endpointConfigurationsDecoded0
    }
}
