// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension LexRuntimeV2ClientTypes {
    /// The state of the user's session with Amazon Lex V2.
    public struct SessionState: Swift.Equatable {
        /// One or more contexts that indicate to Amazon Lex V2 the context of a request. When a context is active, Amazon Lex V2 considers intents with the matching context as a trigger as the next intent in a session.
        public var activeContexts: [LexRuntimeV2ClientTypes.ActiveContext]?
        /// The next step that Amazon Lex V2 should take in the conversation with a user.
        public var dialogAction: LexRuntimeV2ClientTypes.DialogAction?
        /// The active intent that Amazon Lex V2 is processing.
        public var intent: LexRuntimeV2ClientTypes.Intent?
        ///
        public var originatingRequestId: Swift.String?
        /// Map of key/value pairs representing session-specific context information. It contains application information passed between Amazon Lex V2 and a client application.
        public var sessionAttributes: [Swift.String:Swift.String]?

        public init (
            activeContexts: [LexRuntimeV2ClientTypes.ActiveContext]? = nil,
            dialogAction: LexRuntimeV2ClientTypes.DialogAction? = nil,
            intent: LexRuntimeV2ClientTypes.Intent? = nil,
            originatingRequestId: Swift.String? = nil,
            sessionAttributes: [Swift.String:Swift.String]? = nil
        )
        {
            self.activeContexts = activeContexts
            self.dialogAction = dialogAction
            self.intent = intent
            self.originatingRequestId = originatingRequestId
            self.sessionAttributes = sessionAttributes
        }
    }

}
