// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension LexRuntimeV2ClientTypes {
    /// A value that Amazon Lex V2 uses to fulfill an intent.
    public struct Slot: Swift.Equatable {
        /// When the shape value is List, it indicates that the values field contains a list of slot values. When the value is Scalar, it indicates that the value field contains a single value.
        public var shape: LexRuntimeV2ClientTypes.Shape?
        /// The current value of the slot.
        public var value: LexRuntimeV2ClientTypes.Value?
        /// A list of one or more values that the user provided for the slot. For example, if a for a slot that elicits pizza toppings, the values might be "pepperoni" and "pineapple."
        public var values: [LexRuntimeV2ClientTypes.Slot]?

        public init (
            shape: LexRuntimeV2ClientTypes.Shape? = nil,
            value: LexRuntimeV2ClientTypes.Value? = nil,
            values: [LexRuntimeV2ClientTypes.Slot]? = nil
        )
        {
            self.shape = shape
            self.value = value
            self.values = values
        }
    }

}
