// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DeleteTargetInput: Swift.Equatable {
    /// A Boolean value that can be used to delete all associations with this SNS topic. The default value is FALSE. If set to TRUE, all associations between that target and every notification rule in your AWS account are deleted.
    public var forceUnsubscribeAll: Swift.Bool
    /// The Amazon Resource Name (ARN) of the SNS topic to delete.
    /// This member is required.
    public var targetAddress: Swift.String?

    public init (
        forceUnsubscribeAll: Swift.Bool = false,
        targetAddress: Swift.String? = nil
    )
    {
        self.forceUnsubscribeAll = forceUnsubscribeAll
        self.targetAddress = targetAddress
    }
}
