// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension SecurityHubClientTypes.AwsCodeBuildProjectDetails: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case artifacts = "Artifacts"
        case encryptionKey = "EncryptionKey"
        case environment = "Environment"
        case logsConfig = "LogsConfig"
        case name = "Name"
        case serviceRole = "ServiceRole"
        case source = "Source"
        case vpcConfig = "VpcConfig"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let artifacts = artifacts {
            var artifactsContainer = encodeContainer.nestedUnkeyedContainer(forKey: .artifacts)
            for awscodebuildprojectartifactslist0 in artifacts {
                try artifactsContainer.encode(awscodebuildprojectartifactslist0)
            }
        }
        if let encryptionKey = encryptionKey {
            try encodeContainer.encode(encryptionKey, forKey: .encryptionKey)
        }
        if let environment = environment {
            try encodeContainer.encode(environment, forKey: .environment)
        }
        if let logsConfig = logsConfig {
            try encodeContainer.encode(logsConfig, forKey: .logsConfig)
        }
        if let name = name {
            try encodeContainer.encode(name, forKey: .name)
        }
        if let serviceRole = serviceRole {
            try encodeContainer.encode(serviceRole, forKey: .serviceRole)
        }
        if let source = source {
            try encodeContainer.encode(source, forKey: .source)
        }
        if let vpcConfig = vpcConfig {
            try encodeContainer.encode(vpcConfig, forKey: .vpcConfig)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let encryptionKeyDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .encryptionKey)
        encryptionKey = encryptionKeyDecoded
        let artifactsContainer = try containerValues.decodeIfPresent([SecurityHubClientTypes.AwsCodeBuildProjectArtifactsDetails?].self, forKey: .artifacts)
        var artifactsDecoded0:[SecurityHubClientTypes.AwsCodeBuildProjectArtifactsDetails]? = nil
        if let artifactsContainer = artifactsContainer {
            artifactsDecoded0 = [SecurityHubClientTypes.AwsCodeBuildProjectArtifactsDetails]()
            for structure0 in artifactsContainer {
                if let structure0 = structure0 {
                    artifactsDecoded0?.append(structure0)
                }
            }
        }
        artifacts = artifactsDecoded0
        let environmentDecoded = try containerValues.decodeIfPresent(SecurityHubClientTypes.AwsCodeBuildProjectEnvironment.self, forKey: .environment)
        environment = environmentDecoded
        let nameDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .name)
        name = nameDecoded
        let sourceDecoded = try containerValues.decodeIfPresent(SecurityHubClientTypes.AwsCodeBuildProjectSource.self, forKey: .source)
        source = sourceDecoded
        let serviceRoleDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .serviceRole)
        serviceRole = serviceRoleDecoded
        let logsConfigDecoded = try containerValues.decodeIfPresent(SecurityHubClientTypes.AwsCodeBuildProjectLogsConfigDetails.self, forKey: .logsConfig)
        logsConfig = logsConfigDecoded
        let vpcConfigDecoded = try containerValues.decodeIfPresent(SecurityHubClientTypes.AwsCodeBuildProjectVpcConfig.self, forKey: .vpcConfig)
        vpcConfig = vpcConfigDecoded
    }
}
