// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension SecurityHubClientTypes.AwsEcsClusterConfigurationExecuteCommandConfigurationLogConfigurationDetails: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case cloudWatchEncryptionEnabled = "CloudWatchEncryptionEnabled"
        case cloudWatchLogGroupName = "CloudWatchLogGroupName"
        case s3BucketName = "S3BucketName"
        case s3EncryptionEnabled = "S3EncryptionEnabled"
        case s3KeyPrefix = "S3KeyPrefix"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if cloudWatchEncryptionEnabled != false {
            try encodeContainer.encode(cloudWatchEncryptionEnabled, forKey: .cloudWatchEncryptionEnabled)
        }
        if let cloudWatchLogGroupName = cloudWatchLogGroupName {
            try encodeContainer.encode(cloudWatchLogGroupName, forKey: .cloudWatchLogGroupName)
        }
        if let s3BucketName = s3BucketName {
            try encodeContainer.encode(s3BucketName, forKey: .s3BucketName)
        }
        if s3EncryptionEnabled != false {
            try encodeContainer.encode(s3EncryptionEnabled, forKey: .s3EncryptionEnabled)
        }
        if let s3KeyPrefix = s3KeyPrefix {
            try encodeContainer.encode(s3KeyPrefix, forKey: .s3KeyPrefix)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let cloudWatchEncryptionEnabledDecoded = try containerValues.decode(Swift.Bool.self, forKey: .cloudWatchEncryptionEnabled)
        cloudWatchEncryptionEnabled = cloudWatchEncryptionEnabledDecoded
        let cloudWatchLogGroupNameDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .cloudWatchLogGroupName)
        cloudWatchLogGroupName = cloudWatchLogGroupNameDecoded
        let s3BucketNameDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .s3BucketName)
        s3BucketName = s3BucketNameDecoded
        let s3EncryptionEnabledDecoded = try containerValues.decode(Swift.Bool.self, forKey: .s3EncryptionEnabled)
        s3EncryptionEnabled = s3EncryptionEnabledDecoded
        let s3KeyPrefixDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .s3KeyPrefix)
        s3KeyPrefix = s3KeyPrefixDecoded
    }
}
