// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SecurityHubClientTypes {
    /// Details about an WAF WebACL.
    public struct AwsWafWebAclDetails: Swift.Equatable {
        /// The action to perform if none of the rules contained in the WebACL match.
        public var defaultAction: Swift.String?
        /// A friendly name or description of the WebACL. You can't change the name of a WebACL after you create it.
        public var name: Swift.String?
        /// An array that contains the action for each rule in a WebACL, the priority of the rule, and the ID of the rule.
        public var rules: [SecurityHubClientTypes.AwsWafWebAclRule]?
        /// A unique identifier for a WebACL.
        public var webAclId: Swift.String?

        public init (
            defaultAction: Swift.String? = nil,
            name: Swift.String? = nil,
            rules: [SecurityHubClientTypes.AwsWafWebAclRule]? = nil,
            webAclId: Swift.String? = nil
        )
        {
            self.defaultAction = defaultAction
            self.name = name
            self.rules = rules
            self.webAclId = webAclId
        }
    }

}
