// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension CloudTrailClientTypes {
    /// A JSON string that contains a list of insight types that are logged on a trail.
    public struct InsightSelector: Swift.Equatable {
        /// The type of Insights events to log on a trail. The valid Insights type in this release is ApiCallRateInsight.
        public var insightType: CloudTrailClientTypes.InsightType?

        public init (
            insightType: CloudTrailClientTypes.InsightType? = nil
        )
        {
            self.insightType = insightType
        }
    }

}
