// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Specifies a list of trail tags to return.
public struct ListTagsInput: Swift.Equatable {
    /// Reserved for future use.
    public var nextToken: Swift.String?
    /// Specifies a list of trail ARNs whose tags will be listed. The list has a limit of 20 ARNs. The following is the format of a trail ARN. arn:aws:cloudtrail:us-east-2:123456789012:trail/MyTrail
    /// This member is required.
    public var resourceIdList: [Swift.String]?

    public init (
        nextToken: Swift.String? = nil,
        resourceIdList: [Swift.String]? = nil
    )
    {
        self.nextToken = nextToken
        self.resourceIdList = resourceIdList
    }
}
